### ISSUE TITLE
Pressing enter without explicit command causes irb to continue past breakpoint

### ISSUE THREAD

**Issue by mattbrictson** [ruby/irb#1002]
## Description

When using `binding.irb`, if I explicitly type `continue` to continue past a first breakpoint, then pressing <kbd>enter</kbd> by itself will continue past the next breakpoint. I expect pressing <kbd>enter</kbd> should just insert a newline (i.e. increment the irb prompt).

As you can see in the video below, pressing <kbd>enter</kbd> after reaching the first breakpoint just increments the irb prompt, as expected.

However, upon reaching the second breakpoint, pressing <kbd>enter</kbd> immediately causes the interpreter to continue past the breakpoint. This is not expected.

https://github.com/user-attachments/assets/dfa45a50-6d7f-41d7-bda9-cb9520913c5f

## Result of irb_info

```
irb(main):001> irb_info
Ruby version: 3.3.5
IRB version: irb 1.14.0 (2024-07-06)
InputMethod: RelineInputMethod with Reline 0.5.10 and /Users/mbrictson/.inputrc
Completion: Autocomplete, RegexpCompletor
RUBY_PLATFORM: arm64-darwin23
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

macOS Terminal (macOS Sonoma 14.6.1)

## Setting Files

`~/.irbrc` - None

`~/.inputrc`

```
"\e[A": history-search-backward
"\e[B": history-search-forward
$if Bash
  Space: magic-space
$endif
set completion-ignore-case on
set completion-map-case on
set match-hidden-files off
set show-all-if-ambiguous on
set colored-stats on
```

**Comment by st0012** [comment]
It's related to a requested feature: https://github.com/ruby/irb/pull/856

For context, this is what `ruby/debug` does: inserting empty input after stepping commands like `step`, `next`, and `continue`, will repeat the previous command.

And IRB's `continue` command, along with other debugging commands, are simply shortcuts to start an `irb:rdbg` session, which is essentially a `ruby/debug` running IRB as its REPL. So in those sessions we decided to mimic the above behaviour.

**Comment by mattbrictson** [comment]
Ah, I see. It is working as intended then. Thanks for explaining! I'll close the issue.
