### ISSUE TITLE
Array.join("\n") doesn't work without puts/print/p

### ISSUE THREAD

**Issue by utkarsh2102** [ruby/irb#104]
Hi,

Here's one instance:
```
irb(main):001:0> x = [1,12,123]
irb(main):002:0> x.join("\n")
=> "1\n12\n123"
```

However, it works fine if used with `puts`:
```
irb(main):003:0> x = [1,12,123]
irb(main):004:0> puts x.join("\n")
1
12
123
=> nil
```

Shouldn't it be working w/o `puts/print/p`, too?
I'll be happy to raise a PR, too, if you concur with this?
(P.S. I am not sure if that's a bug or a feature)

**Comment by nobu** [comment]
How you expect it to “work”?

**Comment by yuki24** [comment]
This is by design. In your first example, it's the REPL displaying the actual, understandable representation of an object while the second example sends it to STDIO with no modification. They exist for different purposes and I'd be surprised if there is no distinction between these two.

**Comment by utkarsh2102** [comment]
Hi Yuki,

> This is by design. In your first example, it's the REPL displaying the actual, understandable representation of an object while the second example sends it to STDIO with no modification. They exist for different purposes and I'd be surprised if there is no distinction between these two.

Thank you, that makes sense! :)
