### ISSUE TITLE
Non-ASCII input Support

### ISSUE THREAD

**Issue by ParadoxV5** [ruby/irb#110]
My issue might be platform-specific (I’m using Windows 10).
* Windows Terminal: Inputting a non-ASCII character softlocks IRB / the terminal emulator (not even `ctrl+c` does anything).
* `cmd.exe` and `powershell`: Inputting a non-ASCII character crashes either terminal emulator.
All three support non-ASCII insertion outside IRB, so I believe this is an IRB bug.

Note that Windows Terminal is the only terminal emulator I know that this issue persisted (the other two I only tested for reporting this issue).

No impact on USA Rubyists, of course. I only noted this issue after installing a new keyboard layout, and it has occurred to me ever since whenever I forgot to change my keyboard layout.

**Comment by nobu** [comment]
It seems to occur only in cp65001, but not cp932.

**Comment by hikmet517** [comment]
Same issue here on linux.
Distro: ArchLinux
Terminal: Konsole
irb: irb 1.2.4 (2020-05-02)
ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by aycabta** [comment]
@ParadoxV5 @hikmet517 

- Would you try the latest irb gem and reline gem with `gem install irb reline`?
- What is the language setting on the keyboard?
- Which keys did you use and which characters did you type?

**Comment by ParadoxV5** [comment]
How about this:
My steps to reproduce:

0. Install Chinese PinYin IME on your OS OR turn on smart quotes if MacOS
1. In IRB, press `"` under the IME / smart quotes (which maps to `“` and `”` automatically)

**Comment by hikmet517** [comment]
Problem seems to be solved on my system with irb 1.2.7.
My keyboard layout is "Turkish Q" and now I can enter any Turkish characters such as ş, ç, ö.

**Comment by st0012** [comment]
@ParadoxV5 Can you check if this is still a problem with the latest IRB? (You can install it with `gem install irb`).

**Comment by ParadoxV5** [comment]
@st0012 it’s been quite a while since this issue filed originally, but I’ve found no issues with non-ASCIIs these days.
