### ISSUE TITLE
Wrong cursor position when self.to_s is a multi-line string

### ISSUE THREAD

**Issue by hanazuki** [ruby/irb#153]
## Description

When `self.to_s` is a multi-line string or contains newline characters, the cursor is displayed at the wrong column in the IRB prompt. Also, typing any character causes the prompt redrawn at the wrong line.

```console
$ ruby -e '("a\n"*10).instance_eval { binding.irb }'
```

![image](https://user-images.githubusercontent.com/1135690/103073618-44ee8900-460b-11eb-974f-7d2dc66d4a3f.png)

This screenshot shows an IRB prompt with a 10-line string as self and "1" typed in the prompt.
We expected the cursor to be positioned next to the "> " (or next to "1" after typing) and no duplicate prompts.

## Result of irb_info

Built from ruby v3_0_0_rc2 https://github.com/ruby/ruby/commit/a89932799c914d1864fc91f33d6461592dbfd3fb

```
irb(main):001:0> irb_info
=>
Ruby version: 3.0.0
IRB version: irb 1.2.9 (2020-12-22)
InputMethod: ReidlineInputMethod with Reline 0.1.10
```

## Terminal Emulator

- mintty 3.2.0 (Ruby runs on a Linux box over SSH)
- iTerm2 3.4.3 (Ruby runs on macOS)

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`? : Reproduces without .irbrc.

**Comment by hanazuki** [comment]
This didn't happen with the legacy IRB

**Comment by tompng** [comment]
Reported problem is resolved in reline's side by escaping newline character to `\n`, but similar problem still exists.
```ruby
"\r".instance_eval{binding.irb} # wrong cursor position
"\a".instance_eval{binding.irb} # wrong cursor position + many beep sound
# other characters (0x00-0x1F) also cause problem
```

I think promt that includes these characters should not be passed to Reline.
IRB should select how to handle these characters. delete, escape, replace, or any other strategy.
