### ISSUE TITLE
Output only being presented when exit is called

### ISSUE THREAD

**Issue by rafaelfranca** [ruby/irb#185]
All information is on this gif

![Kapture 2021-02-08 at 16 46 13](https://user-images.githubusercontent.com/47848/107285875-c8ceca00-6a2d-11eb-94ac-5037e01cf5b1.gif)

```
Ruby version: 3.0.0
IRB version: irb 1.3.3 (2021-02-07)
InputMethod: ReidlineInputMethod with Reline 0.2.3 
```

**Comment by rafaelfranca** [comment]
It seems to be related with the vscode integrated terminal.

**Comment by aycabta** [comment]
Would you tell me what OS you are running the IRB on?

**Comment by rafaelfranca** [comment]
Sure. It is Linux 5.3.0-1036-gke #38-Ubuntu x86_64. To be fair I think this is a limitation of the vscode integrated terminal. If I try to executed the same steps using ssh over any regular terminal I don't get this behavior.

I'll leave to you if you think it is worth investigating this issue. I'm ok if you decide to close.

**Comment by aycabta** [comment]
I believe that vscode support is very important to the user experience of Ruby.

I can't reproduce it yet. Would you show me the settings under `terminal.integrated.`? For example, mine is;

```json
{
    "terminal.integrated.scrollback": 100,
    "terminal.integrated.automationShell.linux": ""
}
```

**Comment by rafaelfranca** [comment]
I'm using the default config. I didn't have anything set. Now I have:

```
    "terminal.integrated.rendererType": "experimentalWebgl",
    "terminal.integrated.automationShell.linux": "",
```

When I change to `experimentalWebgl` it was fixed.

**Comment by aycabta** [comment]
Just a guess, but I think it was a bug in the vscode terminal. If you reproduce it again, please reopen it.
