### ISSUE TITLE
is it possible to use ruby 3.0 with an older version of irb?

### ISSUE THREAD

**Issue by sdedeo** [ruby/irb#200]
I'm struggling with irb 3.0 (for a number of reasons, e.g., unexpected termination of the session, difficulties cutting and pasting, etc.) I'd love to help people improve irb, and am learning a little of the underlying code, but I'm also needing to use irb for my scientific work. It would be great to have the improved speed and features of ruby 3.0 without the kinks of irb 3.0.

**Comment by metacritical** [comment]
So in your irb console, if you try 

``` >> Gem.default_specifications_dir ``` 

you will get a gemspec location :

```~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/specifications/default/```

just move the ```irb-1.3.0.gemspec``` to another location and uninstall irb.

```gem uninstall irb -v 1.3.0```and then install the irb version you need.

**Comment by marcandre** [comment]
Alternatively, run `bundle exec irb` from a directory with a Gemfile specifying which version of `irb` you want to run.
