### ISSUE TITLE
irb miscalculates nest level when typing do keyword

### ISSUE THREAD

**Issue by Tietew** [ruby/irb#21]
While typing `while`, `until` and `for`, IRB miscalculates indent level after typing `do`.

Without `do`, everything OK.
```
irb(main):001:1* while false
irb(main):002:0> end
=> nil
```

Just after typing `do` (before <kbd>ENTER</kbd>), nest level increased. (■ is cursor)
```
irb(main):001:2* while false do
irb(main):002:1* end
irb(main):003:1* ■
```
```
irb(main):001:2* until true do
irb(main):002:1* end
irb(main):003:1* ■
```
```
irb(main):001:2* for i in [] do
irb(main):002:1* end
irb(main):003:1* ■
```

It doesn't happen with `then`.
```
irb(main):001:1* if true then
irb(main):002:0> end
=> nil
```

Affected: current master
Unaffected: ruby 2.6.3p62 bundled irb

_Original: https://bugs.ruby-lang.org/issues/15994_

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/irb/commit/aa3ea26c403c7d78451f92310c69e20d9489df49.
