### ISSUE TITLE
Ctrl+c can exit irb while in handle_exception phase of REPL.

### ISSUE THREAD

**Issue by mathieulb** [ruby/irb#233]
## Description

if a very lengthy pretty-printing is being displayed, then during at least some portion of that time, Ctrl+c will cause irb to exit, losing all progress in whatever the user was doing, whereas the user would expect Ctrl+c to be trapped as usual.

## Result of irb_info

Ruby version: 3.0.1
IRB version: irb 1.3.5 (2021-04-03)
InputMethod: ReidlineInputMethod with Reline 0.2.5
RUBY_PLATFORM: x86_64-darwin20

## Terminal Emulator

MacOS Terminal.app

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

no

**Comment by mathieulb** [comment]
Actually, here's the stack trace for the exit : 
^C/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:427:in `raise': abort then interrupt! (IRB::Abort)
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:427:in `irb_abort'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:734:in `signal_handle'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:476:in `block in run'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:662:in `write'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:662:in `puts'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:662:in `puts'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:662:in `handle_exception'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:586:in `block (2 levels) in eval_input'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:751:in `signal_status'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:548:in `block in eval_input'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb/ruby-lex.rb:251:in `block (2 levels) in each_top_level_statement'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb/ruby-lex.rb:233:in `loop'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb/ruby-lex.rb:232:in `catch'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:547:in `eval_input'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:481:in `block in run'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:480:in `catch'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:480:in `run'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/irb.rb:409:in `start'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /usr/local/opt/ruby/bin/irb:23:in `load'
	from /usr/local/opt/ruby/bin/irb:23:in `<main>'

**Comment by aycabta** [comment]
I ran `o = Object.new; def o.inspect() = "class A\n  def a\n    3\n  end\nend\n" * 20000; o` and pressed Ctrl-c during outputting the result, but couldn't reproduce it.

```ruby
irb(main):001:0> o = Object.new; def o.inspect() = "class A\n  def a\n    3\n  end\nend\n" * 20000; o
class A
  def a
    3
  end
end
class A
  def a
    3
  end
end
(...snip...)
class A
  def a
    ^C/home/aycabta/ruby/irb/lib/irb.rb:427:in `raise': abort then interrupt! (IRB::Abort)
        from exe/irb:11:in `<main>'
irb(main):007:0>
```

How can I reproduce it?

**Comment by mathieulb** [comment]
I was using the "parse/stack" library (for accessing ParsePlatform databases), which would be hard to test with if you don't have your own Parse db. I believe that I forgot to add «;nil» to the end of a command, so it started printing the contents of a huge array, but I interrupted it while printing, therefore the \#inspect call had already completed. You could try walking up the stack trace (from last item towards the top) and see whether there's any possibility that no begin/rescue would be active for trapping this IRB::Abort. If the stack trace doesn't make sense (doesn't match what I say) or if you otherwise can't figure out, I'll attempt to reproduce the bug in a clearer way. Unfortunately, I didn't keep the transcript of the exact commands I tried, and that's a big mistake, as right now a simple test works and I don't know what's different. irb_info still says exactly the same versions (RUBY_PLATFORM changed because of switching to a different Mac, but that's all).

If you have to close this issue because of insufficient proof, do it and I'll reopen it once I stumble upon it again.

**Comment by tompng** [comment]
Can reproduce with
```
irb(main):001:0> raise StandardError.new.tap { def _1.full_message(...); sleep 1; super(...); end }
(Press Ctrl+c within 1 sec)
```
