### ISSUE TITLE
Unable to change the default behavior of mathematical operator inside irb.

### ISSUE THREAD

**Issue by shanshaji** [ruby/irb#253]
## Description
Unable to change the default behavior of mathematical operator inside `irb`. `irb` gets stuck when trying to change the behavior and be closed by ctrl + c.

## Result of irb_info
```
irb(main):001:1* class Integer
irb(main):002:2*   def +(num)
irb(main):003:2*     self - num
irb(main):004:1*   end
irb(main):005:0> end
=> :+
```

Ruby version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
IRB version: irb 1.3.6 (2021-06-19)
```

## Terminal Emulator

Terminator

**Comment by ima1zumi** [comment]
irb is written in Ruby and also uses `+`.
If you redefine `+`, the behavior of `+` in irb code will change, and it will not work. 😢

**Comment by tompng** [comment]
In ruby, (not only in irb) you can use refinements to overwrite the default behavior safely, or you can carefully overwrite by open class in your own risk.
```ruby
irb(main):001:1* using (
irb(main):002:2*   Module.new do
irb(main):003:3*     refine Integer do
irb(main):004:4*       def +(n)
irb(main):005:4*         (to_s+n.to_s).to_i
irb(main):006:3*       end
irb(main):007:2*     end
irb(main):008:1*   end
irb(main):009:0> )
=> main
irb(main):010:0> 12 + 34
=> 1234
```
