### ISSUE TITLE
When pressing the alt key it prints `^[`

### ISSUE THREAD

**Issue by P3t3rU5** [ruby/irb#255]
## Description

When pressing the alt key it prints `^[`

What are your expected behavior and actual behavior of your environment?

Not to print any character while pressing alt

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.0.1
IRB version: irb 1.3.6 (2021-06-19)
InputMethod: ReidlineInputMethod with Reline 0.2.6
.irbrc path: C:/Users/pedro/.irbrc
RUBY_PLATFORM: x64-mingw32
```

## Terminal Emulator

PowerShell in Windows Terminal
Command Prompt in Windows Terminal

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

~/.irbrc
```
require 'irb/ext/save-history'
require 'irb/completion'
IRB.conf[:SAVE_HISTORY] = 200
```

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/reline/pull/299.
