### ISSUE TITLE
End of line is black even default background is white or some other color

### ISSUE THREAD

**Issue by sevenc-nanashi** [ruby/irb#260]
## Description

I'm using powershell with white background, But irb shows black background.
![image](https://user-images.githubusercontent.com/59691627/126291446-76c5049c-2b6c-4f1b-bc3f-801abe07f2df.png)
![image](https://user-images.githubusercontent.com/59691627/126291650-28445e1a-86b4-4533-af43-7db46f7d1897.png)

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.0.0
IRB version: irb 1.3.6 (2021-06-19)
InputMethod: ReidlineInputMethod with Reline 0.2.6
.irbrc path: C:/Users/(redacted)/.irbrc
RUBY_PLATFORM: i386-mingw32
```

## Terminal Emulator

Powershell

## Setting Files

(None)

**Comment by nobu** [comment]
How do you set the background color?

**Comment by sevenc-nanashi** [comment]
property of Powershell.
