### ISSUE TITLE
Spaces at the beginning of lines are stuffed when using heredoc

### ISSUE THREAD

**Issue by sanfrecce-osaka** [ruby/irb#265]
### Expected

Spaces at the beginning of line are not stuffed when using heredoc

```
irb(main):001:0" foo = <<FOO
irb(main):002:0"   abcdefg
irb(main):003:0> FOO
=> "  abcdefg\n"
```

#### Case1

Spaces at the beginning of lines are packed after finalization

[![Image from Gyazo](https://i.gyazo.com/a6d1e8a05253eacb44a150431ed30120.gif)](https://gyazo.com/a6d1e8a05253eacb44a150431ed30120)

#### Case2

The following will cause the spaces at the beginning of the line to be stuffed

1. Input spaces at the beginning of line and start a new line
2. Enter the delete key

[![Image from Gyazo](https://i.gyazo.com/0b22fe5aaf8004d92f9445f25ee1d102.gif)](https://gyazo.com/0b22fe5aaf8004d92f9445f25ee1d102)

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.0.1
IRB version: irb 1.3.6 (2021-06-19)
InputMethod: ReidlineInputMethod with Reline 0.2.5
.irbrc path: /Users/moritsukamasatoshi/.irbrc
RUBY_PLATFORM: x86_64-darwin20
```

## Terminal Emulator

iTerm2 3.4.6

## Setting Files

Not used

**Comment by aycabta** [comment]
Thank you for your reporting, this is fixed by https://github.com/ruby/irb/pull/291.
