### ISSUE TITLE
Can I put irb configs under XDG_CONFIG_HOME?

### ISSUE THREAD

**Issue by molleweide** [ruby/irb#277]
Hi,

Is it possible to put config files under XDG_CONFIG_HOME with irb?

**Comment by olleolleolle** [comment]
@molleweide Does this help?
https://github.com/ruby/irb/search?q=XDG_CONFIG_HOME

**Comment by molleweide** [comment]
Thanks for your reply.
I also just now saw that irb is supported under arch wiki. 
My apologies for not having done enough research.

**Comment by olleolleolle** [comment]
@molleweide If we consult the documentation, it _could_ use a note that XDG locations are supported, too! 

https://docs.ruby-lang.org/en/3.0.0/IRB.html#module-IRB-label-Configuration
