### ISSUE TITLE
problem with running irb

### ISSUE THREAD

**Issue by basharbachir** [ruby/irb#28]
hello, 

when i type irb inside the command line ,i get this error message
i reinstalled ruby installer again and nothing has been fixed
`

C:\WINDOWS\system32>irb
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4442: [BUG] Segmentation fault
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0032 p:---- s:0167 e:000166 CFUNC  :call
c:0031 p:0018 s:0161 e:000160 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4442
c:0030 p:0027 s:0156 e:000155 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:1863
c:0029 p:0192 s:0147 e:000146 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:1997
c:0028 p:0096 s:0138 e:000137 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:2564
c:0027 p:0024 s:0134 e:000133 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:3849
c:0026 p:0033 s:0130 e:000129 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4868
c:0025 p:0066 s:0124 e:000123 METHOD C:/Ruby26-x64/lib/ruby/site_ruby/readline.rb:45
c:0024 p:0037 s:0116 e:000115 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/input-method.rb:151
c:0023 p:0010 s:0111 e:000110 BLOCK  C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:473
c:0022 p:0025 s:0107 e:000106 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:647
c:0021 p:0008 s:0101 e:000100 BLOCK  C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:472
c:0020 p:0011 s:0098 e:000097 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:189
c:0019 p:0010 s:0093 e:000092 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:104
c:0018 p:0018 s:0088 e:000087 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/slex.rb:206
c:0017 p:0035 s:0079 e:000078 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/slex.rb:76
c:0016 p:0031 s:0073 e:000072 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:292
c:0015 p:0142 s:0068 e:000067 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:266
c:0014 p:0015 s:0061 e:000060 BLOCK  C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:236 [FINISH]
c:0013 p:---- s:0057 e:000056 CFUNC  :loop
c:0012 p:0006 s:0053 e:000052 BLOCK  C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:232 [FINISH]
c:0011 p:---- s:0050 e:000049 CFUNC  :catch
c:0010 p:0012 s:0045 e:000044 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:231
c:0009 p:0034 s:0041 E:0009d8 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:489
c:0008 p:0005 s:0036 e:000035 BLOCK  C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:428 [FINISH]
c:0007 p:---- s:0033 e:000032 CFUNC  :catch
c:0006 p:0064 s:0028 E:0002b8 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:427
c:0005 p:0102 s:0023 e:000022 METHOD C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:383
c:0004 p:0019 s:0017 e:000016 TOP    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11 [FINISH]
c:0003 p:---- s:0014 e:000013 CFUNC  :load
c:0002 p:0120 s:0009 E:001938 EVAL   C:/Ruby26-x64/bin/irb.cmd:31 [FINISH]
c:0001 p:0000 s:0003 E:0017b0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
C:/Ruby26-x64/bin/irb.cmd:31:in `<main>'
C:/Ruby26-x64/bin/irb.cmd:31:in `load'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:383:in `start'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:427:in `run'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:427:in `catch'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:428:in `block in run'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:266:in `lex'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:292:in `token'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/slex.rb:76:in `match'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/slex.rb:206:in `match_io'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:104:in `getc'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb:189:in `buf_input'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:472:in `block in eval_input'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb:473:in `block (2 levels) in eval_input'
C:/Ruby26-x64/lib/ruby/2.6.0/irb/input-method.rb:151:in `gets'
C:/Ruby26-x64/lib/ruby/site_ruby/readline.rb:45:in `readline'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4868:in `readline'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:3849:in `rl_initialize'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:2564:in `readline_initialize_everything'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:1997:in `_rl_init_terminal_io'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:1863:in `_rl_get_screen_size'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4442:in `call'
C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb:4442:in `call'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007ff835efc144]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x93) [0x00007ff8331b8ba3]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_bugreport+0x2eb) [0x000000006a680c4b]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_bug_context+0x70) [0x000000006a4ce9f0]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_safe_obj+0x4d0) [0x000000006a5e4460]
 [0x0000000000402426]
C:\WINDOWS\System32\msvcrt.dll(_C_specific_handler+0x98) [0x00007ff833fc8048]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007ff835f011ff]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlRaiseException+0x399) [0x00007ff835eca289]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007ff835effe6e]
C:\WINDOWS\System32\KERNELBASE.dll(GetConsoleScreenBufferInfo+0x26) [0x00007ff83318b4f6]
C:\Ruby26-x64\bin\ruby_builtin_dlls\libffi-6.dll(ffi_call_win64+0x97) [0x000000006b744797]
C:\Ruby26-x64\bin\ruby_builtin_dlls\libffi-6.dll(ffi_call+0x47) [0x000000006b7443a7]
C:\Ruby26-x64\lib\ruby\2.6.0\x64-mingw32\fiddle.so(Init_fiddle+0xb28) [0x0000000063d82dd8]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_thread_call_without_gvl+0x58) [0x000000006a62da48]
C:\Ruby26-x64\lib\ruby\2.6.0\x64-mingw32\fiddle.so(Init_fiddle+0xe3f) [0x0000000063d830ef]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x131) [0x000000006a65df51]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xd01) [0x000000006a6685f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0xa02) [0x000000006a673102]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0x21f) [0x000000006a666c8f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_f_eval+0x566) [0x000000006a669c16]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_rescue2+0x135) [0x000000006a4d7ba5]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_f_notimplement+0xbe2) [0x000000006a659db2]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x131) [0x000000006a65df51]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xd01) [0x000000006a6685f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0xaa5) [0x000000006a6731a5]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0x21f) [0x000000006a666c8f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_yield_1+0x64f) [0x000000006a66a64f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_block_call+0x19d) [0x000000006a66216d]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_catch+0xa1) [0x000000006a6623d1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x131) [0x000000006a65df51]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xd01) [0x000000006a6685f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0xaa5) [0x000000006a6731a5]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0x21f) [0x000000006a666c8f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_yield_1+0x64f) [0x000000006a66a64f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_block_call+0x19d) [0x000000006a66216d]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_catch+0xa1) [0x000000006a6623d1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x131) [0x000000006a65df51]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xd01) [0x000000006a6685f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0xaa5) [0x000000006a6731a5]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0x9f5) [0x000000006a667465]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_iseqw_local_variables+0x100c) [0x000000006a528c8c]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_iseqw_local_variables+0x132b) [0x000000006a528fab]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x131) [0x000000006a65df51]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xd01) [0x000000006a6685f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0xa02) [0x000000006a673102]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0x21f) [0x000000006a666c8f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_call_end_proc+0x15c) [0x000000006a4d291c]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(ruby_run_node+0x59) [0x000000006a4d7179]
 [0x0000000000402d27]
 [0x00000000004013b4]
 [0x000000000040150b]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007ff834057bd4]

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/encdb.so
    5 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/transdb.so
    6 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/windows_1252.so
    7 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/rbconfig.rb
    8 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/compatibility.rb
    9 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/defaults.rb
   10 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/deprecate.rb
   11 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/errors.rb
   12 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/version.rb
   13 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/requirement.rb
   14 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/platform.rb
   15 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/basic_specification.rb
   16 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/stub_specification.rb
   17 C:/Ruby26-x64/lib/ruby/2.6.0/delegate.rb
   18 C:/Ruby26-x64/lib/ruby/2.6.0/uri/rfc2396_parser.rb
   19 C:/Ruby26-x64/lib/ruby/2.6.0/uri/rfc3986_parser.rb
   20 C:/Ruby26-x64/lib/ruby/2.6.0/uri/common.rb
   21 C:/Ruby26-x64/lib/ruby/2.6.0/uri/generic.rb
   22 C:/Ruby26-x64/lib/ruby/2.6.0/uri/file.rb
   23 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ftp.rb
   24 C:/Ruby26-x64/lib/ruby/2.6.0/uri/http.rb
   25 C:/Ruby26-x64/lib/ruby/2.6.0/uri/https.rb
   26 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ldap.rb
   27 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ldaps.rb
   28 C:/Ruby26-x64/lib/ruby/2.6.0/uri/mailto.rb
   29 C:/Ruby26-x64/lib/ruby/2.6.0/uri.rb
   30 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/specification_policy.rb
   31 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/util/list.rb
   32 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/stringio.so
   33 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/specification.rb
   34 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/exceptions.rb
   35 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/singleton.rb
   36 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime.rb
   37 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/msys2_installation.rb
   38 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/fiddle.so
   39 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle/function.rb
   40 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle/closure.rb
   41 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle.rb
   42 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/dll_directory.rb
   43 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/utf_16le.so
   44 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/utf_16_32.so
   45 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/defaults/operating_system.rb
   46 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/util.rb
   47 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb
   48 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/dependency.rb
   49 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb
   50 C:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb
   51 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb
   52 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_warn.rb
   53 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems.rb
   54 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/path_support.rb
   55 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/version.rb
   56 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/core_ext/name_error.rb
   57 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/levenshtein.rb
   58 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/jaro_winkler.rb
   59 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb
   60 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/clas
s_name_checker.rb
   61 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/vari
able_name_checker.rb
   62 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   63 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   64 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   65 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/null_checker.rb
   66 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/formatters/plain_formatter.rb
   67 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean.rb
   68 C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb
   69 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/request_set/gem_dependency_api.rb
   70 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/request_set/lockfile/parser.rb
   71 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/request_set/lockfile/tokenizer.rb
   72 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/request_set/lockfile.rb
   73 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/request_set.rb
   74 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/gem_metadata.rb
   75 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/errors.rb
   76 C:/Ruby26-x64/lib/ruby/2.6.0/set.rb
   77 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/action.rb
   78 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
   79 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/add_vertex.rb
   80 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/delete_edge.rb
   81 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
   82 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/set_payload.rb
   83 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/tag.rb
   84 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/log.rb
   85 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/vertex.rb
   86 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb
   87 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/state.rb
   88 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/modules/specification_provider.rb
   89 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/resolution_state.rb
   90 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb
   91 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb
   92 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb
   93 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/modules/ui.rb
   94 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo.rb
   95 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/molinillo.rb
   96 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/activation_request.rb
   97 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/conflict.rb
   98 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/dependency_request.rb
   99 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/requirement_list.rb
  100 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/stats.rb
  101 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/set.rb
  102 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/api_set.rb
  103 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb
  104 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/best_set.rb
  105 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/current_set.rb
  106 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/git_set.rb
  107 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/index_set.rb
  108 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb
  109 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/lock_set.rb
  110 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/vendor_set.rb
  111 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/source_set.rb
  112 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/specification.rb
  113 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/spec_specification.rb
  114 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/api_specification.rb
  115 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/git_specification.rb
  116 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/index_specification.rb
  117 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/installed_specification.rb
  118 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/local_specification.rb
  119 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/lock_specification.rb
  120 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver/vendor_specification.rb
  121 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/resolver.rb
  122 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/git.rb
  123 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/installed.rb
  124 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/specific_file.rb
  125 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/local.rb
  126 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/lock.rb
  127 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source/vendor.rb
  128 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/source.rb
  129 C:/Ruby26-x64/lib/ruby/2.6.0/e2mmap.rb
  130 C:/Ruby26-x64/lib/ruby/2.6.0/irb/init.rb
  131 C:/Ruby26-x64/lib/ruby/2.6.0/irb/workspace.rb
  132 C:/Ruby26-x64/lib/ruby/2.6.0/irb/inspector.rb
  133 C:/Ruby26-x64/lib/ruby/2.6.0/irb/src_encoding.rb
  134 C:/Ruby26-x64/lib/ruby/2.6.0/irb/magic-file.rb
  135 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/euc_jp.so
  136 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/windows_31j.so
  137 C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline/version.rb
  138 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/etc.so
  139 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/single_byte.so
  140 C:/Ruby26-x64/lib/ruby/site_ruby/rbreadline.rb
  141 C:/Ruby26-x64/lib/ruby/site_ruby/readline.rb
  142 C:/Ruby26-x64/lib/ruby/2.6.0/irb/input-method.rb
  143 C:/Ruby26-x64/lib/ruby/2.6.0/irb/output-method.rb
  144 C:/Ruby26-x64/lib/ruby/2.6.0/irb/context.rb
  145 C:/Ruby26-x64/lib/ruby/2.6.0/irb/extend-command.rb
  146 C:/Ruby26-x64/lib/ruby/2.6.0/irb/notifier.rb
  147 C:/Ruby26-x64/lib/ruby/2.6.0/irb/slex.rb
  148 C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-token.rb
  149 C:/Ruby26-x64/lib/ruby/2.6.0/irb/ruby-lex.rb
  150 C:/Ruby26-x64/lib/ruby/2.6.0/irb/locale.rb
  151 C:/Ruby26-x64/lib/ruby/2.6.0/irb/version.rb
  152 C:/Ruby26-x64/lib/ruby/2.6.0/irb.rb
  153 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/irbrc_predefiner.rb
  154 C:/Ruby26-x64/lib/ruby/2.6.0/irb/ext/save-history.rb
  155 C:/Ruby26-x64/lib/ruby/2.6.0/irb/completion.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

`

thanks

**Comment by nobu** [comment]
It is an issue of rbreadline.

**Comment by foreverqihe** [comment]
Hi @nobu , I also encountered this on windows 10. I tried 2.4 ~ 2.6 but none of these versions works.
Anything we can do to make it work? We can't use 2.7 as some dependency can't run on 2.7.

Cheers,
He

**Comment by nobu** [comment]
This is an issue of rb-readline, which calls Windows API by fiddle.
Since readline gem has been released as a wrapper of reline gem now, you may workaround with it.

**Comment by foreverqihe** [comment]
Hi @nobu ,

  Thank you for your reply. I tried to install the readline gem but still got the segment fault. Any idea how to workaround?

Regards,
He

**Comment by foreverqihe** [comment]
Updated irb to latest and it works.
