### ISSUE TITLE
False to start irb when run `irb` in terminal. Please help me how to fix it

### ISSUE THREAD

**Issue by David-Roark** [ruby/irb#319]
## Description
when I type `irb` on terminal, it shows this error
```
<internal:/home/david-roark/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': libffi.so.7: cannot open shared object file: No such file or directory - /home/david-roark/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/x86_64-linux/fiddle.so (LoadError)
```
## Info
Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
Gem version: 3.2.22
rvm version: 1.29.12
OS: Ubuntu 21.10 x86_64
Terminal: x-terminal-emul

**Comment by osyo-manga** [comment]
hi.
This has been fixed in https://github.com/ruby/reline/pull/378 to avoid crashing.
However, https://github.com/ruby/reline/pull/378 has not yet been released.
see: 
https://github.com/ruby/reline/issues/344

**Comment by David-Roark** [comment]
Thanks @osyo-manga
