### ISSUE TITLE
Change default completion background color

### ISSUE THREAD

**Issue by ianks** [ruby/irb#328]
## Description

When starting IRB in Ruby 3.1, autocomplete suggestions are shown but hard to read due to the default background color. Ideally, the default background color settings would ensure enough contrast to make the text legible.

<img width="246" alt="Screen Shot 2022-01-08 at 12 22 23 PM" src="https://user-images.githubusercontent.com/3303032/148653612-e3dff786-1a10-4923-a0eb-3975cae10a7f.png">

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

ex.)

```
irb(main):001:0> irb_info
=>
Ruby version: 3.1.0                            
IRB version: irb 1.4.1 (2021-12-25)            
InputMethod: ReidlineInputMethod with Reline 0.3.0
RUBY_PLATFORM: arm64-darwin21                  
LANG env: en_US.UTF-8                          
East Asian Ambiguous Width: 1                  
```

## Terminal Emulator

VSCode terminal

## Setting Files

> Are you using `~/.irbrc` and `~/.inputrc`?

No I am not

**Comment by ianks** [comment]
I believe https://github.com/ruby/irb/issues/328 would allow for this

**Comment by kaiquekandykoga** [comment]
> I believe #328 would allow for this

The link provided is redirecting to the same page.

**Comment by osyo-manga** [comment]
This?
https://github.com/ruby/reline/pull/413

**Comment by sshock** [comment]
Making it configurable would be great!  Looking forward to https://github.com/ruby/reline/pull/413 and https://github.com/ruby/irb/pull/337 being approved and merged!

But the default should be fixed too.  White text on a bright cyan background is just plain awful.  Can we at least make the background dark cyan?

**Comment by pocari** [comment]
Having made the [changes](https://github.com/ruby/reline/pull/413/commits/9bf4979ecd53f3a22909491e150f351d727b0e2a) as [advised](https://github.com/ruby/reline/pull/413#discussion_r874176336) by @St0012, it is now simple to change the default background and foreground color. Now it is just a matter of specifying the appropriate value in the block that sets the default value.

**Comment by ima1zumi** [comment]
Fixed https://github.com/ruby/reline/pull/552
