### ISSUE TITLE
Incorrect completion suggestions

### ISSUE THREAD

**Issue by ashmaroli** [ruby/irb#329]
## Description

Expected to get valid suggestions based on referenced object.

### Sample Code:

```ruby
Lorem = Class.new

module Foo
  def lipsum
    @lipsum ||= Lorem.new
  end
end

require 'irb'
require 'irb/completion'

puts "Initializing with IRB #{IRB::VERSION}..\n\n"

IRB.setup(nil)
IRB::Irb.new.tap do |irb|
  irb.context.main.extend(Foo)
end.run
```
### Actual Result

![irb](https://user-images.githubusercontent.com/12479464/148677629-0798154c-f592-44e1-9248-086794a682e9.png)

Note that even though `lipsum` references an instance of an `Lorem` which is simply a base class, the completion suggestion displays
methods not defined in `Lorem` or any of the ancestors of `Lorem`.

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 2.7.5
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.1
.irbrc path: C:/Users/[USERNAME]/.irbrc
RUBY_PLATFORM: x64-mingw32
East Asian Ambiguous Width: 3
Code page: 437
```

## Terminal Emulator

`cmd.exe` on Windows

## Setting Files

Using just `~/.irbrc`.

**Comment by aycabta** [comment]
Due to side effects, completion of method call results is not possible at the moment. Please see [the corresponding implementation](https://github.com/ruby/irb/blob/bd597bcde0858d5ec86f2c5295df4893dc9ff08b/lib/irb/completion.rb#L320-L328).

**Comment by ashmaroli** [comment]
> Please see [the corresponding implementation](https://github.com/ruby/irb/blob/bd597bcde0858d5ec86f2c5295df4893dc9ff08b/lib/irb/completion.rb#L320-L328).

@aycabta Thank you for responding. Could you also point me to the test coverage for those set of lines?
(Just curious about deducing the rationale and expectations around the particular case).

**Comment by tompng** [comment]
Implementing completion for the provided sample code is extremely difficult because it needs one of these to determine the return value of method `ipsum` is.
- Perform static code analyze for every code evaluated inside IRB
- Analyze `RubyVM::InstructionSequence.of(method(:ipsum))`

Closing as not planned.
However, the new type-completor (#734) will provide better completion for some cases.
