### ISSUE TITLE
writing square brackers on Czech keyboard (Windows)

### ISSUE THREAD

**Issue by KoleckOLP** [ruby/irb#331]
## Description

What are your expected behavior and actual behavior of your environment?

When I press Alt+F I should get [
When I press Alt+G I should get ]
That's standart on Czech keyboards other software fully supports this 

This is what happens instead:
![image](https://user-images.githubusercontent.com/22729896/149296323-89109ca4-340f-4043-99a0-e6add51c6509.png)

This is what should happen (works absolutely fine in python):
![image](https://user-images.githubusercontent.com/22729896/149296413-c9e5404c-6a19-48f0-a6aa-2022b7ffcb2a.png)

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

ex.)

```
irb(main):001:0> irb_info
=>
Ruby version: 3.1.0
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.0
.irbrc path: H://.irbrc
RUBY_PLATFORM: x64-mingw-ucrt
East Asian Ambiguous Width: 1
Code page: 852
```

## Terminal Emulator

What's your terminal emulator?

cmd.exe, powershell, pwsh7

I can't test it in Windows terminal right now.

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

I don't think so, everything should be default.

**Comment by kurukuruk** [comment]
I have the same problem with a french keyboard.
