### ISSUE TITLE
Can't override Kernel#` (backtick operator) due to parsing bug

### ISSUE THREAD

**Issue by pxeger** [ruby/irb#334]
## Description

It is a little-known feature of Ruby that you can override the behaviour of the backtick <code>&#96;&#96;</code> operator (whose default behaviour is to run a shell command), by redefining <code>Kernel#&#96;</code>, as follows:

```ruby
`echo hi`
# => hi
def `(x)
  # demo that it has been overriden by executing the command in reverse
  system(x.reverse)
end
`ih ohce`
# => hi
```

However, you cannot type this code into `irb`, because it gets the parsing wrong and won't let you finish entering the definition:

```ruby
irb(main):008:1` def `(x)
irb(main):009:1`   system(x.reverse)
irb(main):010:1` end
irb(main):011:-` 
irb(main):012:0` 
irb(main):013:0` 
irb(main):014:0` `
irb(main):012:0` `
irb(main):013:0` 
^C
irb(main):008:0>
```

The only way out is Ctrl+C, and after that the defintion still hasn't been executed.

As a workaround, you can use `eval`:

```
irb(main):008:1" eval("def `(x)
irb(main):009:1"   system(x.reverse)
irb(main):010:1" end")
=> :`
irb(main):011:0> `ih ohce`
hi
```

But this is not ideal.

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.0.3
IRB version: irb 1.3.6 (2021-06-19)
InputMethod: ReidlineInputMethod with Reline 0.2.5
RUBY_PLATFORM: x86_64-linux
```

## Terminal Emulator

[kitty](https://github.com/kovidgoyal/kitty)

## Setting Files

No

**Comment by st0012** [comment]
This has been fixed in #390, so closing now.

```
irb(main):001:1* def `(x)
irb(main):002:1*   puts x
irb(main):003:0> end
=> :`
irb(main):004:0> `foo`
foo
=> nil
```
