### ISSUE TITLE
IRB autocomplete is not helpful once you are chaining, change or option to disable?

### ISSUE THREAD

**Issue by jrochkind** [ruby/irb#339]
I like the new IRB autocomplete when it's supplying relevant methods.  Which it can only do for an initial reference. 

If I type `1.`, then it shows methods which actually exist on `Integer`, because it knew the type/class of the reference. This is useful. 

But when you add more `.` to chain methods, it keeps providing suggestions, but because IRB has no real way to know the class/type of the reference at this point -- it seems to be supplying every possible method on any possible type of object currently loaded. Plus constants. And some classes (not sure if it's all of them).  Where most of the things it suggests, if you chose them you'd get a NoMethodError.  

I find this overwhelming and not helpful. I think I am not alone. 

I think it may be worth considering disabling "chained" autocomplete like this.  Alternately, would it be possible to have an `IRB.conf` value that disables just "chained" autocomplete, while leaving the autocomplete on a primary "known class" initial reference?

**Comment by sshock** [comment]
+1

**Comment by blowfishpro** [comment]
I wonder if this is the underlying reason why autocomplete can get unusably slow in reasonably large projects.  It does seem like that only happens on chaining.  Makes sense if it's trying to display a giant list of symbols every time you type.
