### ISSUE TITLE
Can't launch since 1.4.0

### ISSUE THREAD

**Issue by felipec** [ruby/irb#342]
Since 1.4.0 I'm unable to launch `irb`. I get this error:

```
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rdoc (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/irb-1.4.1/lib/irb/input-method.rb:17:in `<top (required)>'
```

I don't have `rdoc`, and I don't see why it should be hard dependency.

**Comment by Maumagnaguagno** [comment]
I had the same error and installed ``rdoc`` to solve it.
The error is related to commit 0267004.
Maybe the ``require 'rdoc'`` from _lib/irb/input-method.rb_ can be removed from line 17 as there is already a ``rescue LoadError`` at line 315 for ``rdoc``.

**Comment by junaruga** [comment]
@felipec Are you using Fedora Ruby RPM package where the the irb (`rubygem-irb` RPM package)'s rdoc (`rubygem-rdoc` RPM package) is optional?

if it is, the solution for now is to run `sudo dnf install rubygem-rdoc`.

The issue was fixed on the latest master branch on this IRB project.

**Comment by felipec** [comment]
@junaruga No, I'm using Arch Linux. The issue seems to be fixes because `ruby` requires `ruby-rdoc` now. I don't think it should, but oh well, at least it works.

**Comment by junaruga** [comment]
> No, I'm using Arch Linux. The issue seems to be fixes because ruby requires ruby-rdoc now. I don't think it should, but oh well, at least it works.

OK. I am not sure if the Arch package system has a concept of soft dependency. In Fedora, the packaging system called RPM has a concept of "weak dependency" that is like soft dependency. Users can select if they will download weak dependencies of the main package by the packaging command's configuration setting. The `rubygem-rdoc` RPM is a weak dependency of the `rubygem-irb` RPM now.

**Comment by junaruga** [comment]
Fixed at https://github.com/ruby/irb/commit/54c8df06ff9e161012f89d19a4e3aa2e0e37e1b0 and https://github.com/ruby/irb/commit/b24852058fc87c940252c8a711c60ae2eb298082 .

**Comment by felipec** [comment]
@junaruga Yes, pacman does have optional depends, but for some reason the maintainer of the packaged opted to not make them optional: [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/ruby/trunk/PKGBUILD#L149).
