### ISSUE TITLE
Ruby IRB (REPL) screen wrap around to first line when hitting bottom of screen in Windows Terminal

### ISSUE THREAD

**Issue by eabase** [ruby/irb#343]
## Description

Screen wrap around to first line when hitting bottom of screen.

Issue was determined to be a Ruby issues, by MS here:
* https://github.com/microsoft/terminal/issues/12283

### Expected Behavior

that screen scroll down normally

### Actual Behavior

wraps to top of screen and overwrite what was there before.

**Does not happen in Powershell (pwsh) where buffer is set to max `9001`**

### Steps to reproduce

Run irb.bat

Keep hitting return until you get past end of last line in terminal.
Prompt then starts overwriting previous text on top of the screen.

---

## Result of irb_info

```
Ruby version: 3.1.0
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.0
RUBY_PLATFORM: x64-mingw-ucrt
East Asian Ambiguous Width: 1
Code page: 65001
```

## Terminal Emulator

What's your terminal emulator?

1. `Windows Terminal` with *default* buffer settings (being equal to screen)
2. WT + WSL

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

**No**

---
Possibly relevant terminal settings:

```
-----------------------------------------------------------------------
  PowerShell Version    : 7.2.1
  OS Name               : Microsoft Windows 10 Home (64-bit)
  OS Version            : 10.0.19042  [2021-06-28 07:45:15 PM]
  OS BuildLabEx         : 19041.1
  OS HAL                : 10.0.19041.1151
  OS Kernel             : 10.0.19041.1466
  OS UBR                : 1466
  -------------------------------------------------------
  ExecutionPolicy:
      MachinePolicy     : Undefined
      UserPolicy        : Undefined
      Process           : Undefined
      CurrentUser       : Bypass
      LocalMachine      : RemoteSigned
  Firewall:
      Status            : OK
  Console Settings:
      Type              : ConsoleHost
      OutputEncoding    : Unicode (UTF-8)
      Color Capability  : TRUECOLOR
      Registry VT Level : 1
      CodePage (input)  : 65001
      CodePage (output) : 65001
      ConInMode         : 0x1f7
      ConOutMode        : 0x7
      Buffer Size (W H) : 160 50
      PSReadLine version: 2.2.0-beta5

```

**Comment by eabase** [comment]
Using the WT debug we can inspectthe ESC sequences sent from IRB.

![image](https://user-images.githubusercontent.com/52289379/151890574-30afa731-881c-4974-9405-af4a8193d30f.png)

This is hard to see, so we enlarge...

![image](https://user-images.githubusercontent.com/52289379/151891069-ab32f64d-744d-46d8-a4d5-e1faa4082a18.png)

Here we see that the following sequence is being sent when hitting return on the last line:

```bash
# Where I used:
# \e = ESC
# \n = Line Feed (LF) = New Line (NL)
# \r = Carriage Return (CR)
# \f = Form Feed (FF)
```

```bash
irb(main):050:0>
\e[K
\r
\e[?25l
\n
\e[H
irb(main):051:0>
_________________________________________
\e[50;1H
\e[1;18H
\[?25h
```

Where I used:
- `\e = ESC`
- `\n = Line Feed (LF)` = New Line (NL)
- `\r = Carriage Return (CR)`
- `\f = Form Feed (FF)`

So what does it mean?
```bash
\e[1C		# Cursor forward (Right) by 1
...

\e[K		# Replace all text on the line with the cursor specified by <n> with space characters
\r
\e[?25l 	# Hide the cursor
\n
\e[H 		# = \e[1;1H = Move cursor to (1,1) coordinate within the viewport
irb(main):051:0>
# ' ' * 64
\e[50;1H 	# Move cursor to line 1, column 50 
\e[1;18H 	# Move cursor to line 18, column 1 
\[?25h 		# Show the cursor
```

Clearly there is a lot weird stuff going on there...
* Why writing the prompt (text) twice?
* Why moving the cursor back and forth without anything in between?
* Why hide and show the cursor?

This may also be the reason why pasting code is so slow in IRB...

**Comment by Erquint** [comment]
I confirm experiencing this annoying issue and proceed to downgrade promptly.

**Comment by YO4** [comment]
Reline 0.3.0 contains wrong code that misidentifies the cursor position. 
Would you try reline 0.3.1?

**Comment by eabase** [comment]
@YO4 
what is 'reline'? Link please.
