### ISSUE TITLE
Completion: Suggestions seem to be in a strange order

### ISSUE THREAD

**Issue by rjschof** [ruby/irb#349]
## Description
When starting IRB (1.4.1) in Ruby 2.7+, the tab completion suggestions seem to be in a strange order: 

<img alt="Screen Shot 2022-01-08 at 12 22 23 PM" width="246" src="https://user-images.githubusercontent.com/3303032/148653612-e3dff786-1a10-4923-a0eb-3975cae10a7f.png">

The way this used to work, `require` used to appear before `require_relative` in the list of completion suggestions.

## Result of irb_info

```
irb(main):001:0> irb_info
Ruby version: 2.7.5                            
IRB version: irb 1.4.1 (2021-12-25)            
InputMethod: ReidlineInputMethod with Reline 0.3.1
RUBY_PLATFORM: arm64-darwin21                  
LANG env: en_US.UTF-8                          
East Asian Ambiguous Width: 1 
```

## Terminal Emulator
iTerm2

## Setting Files
None.

**Comment by st0012** [comment]
I think this may have been fixed by https://github.com/ruby/irb/pull/379

<img width="252" alt="截圖 2022-10-09 16 22 48" src="https://user-images.githubusercontent.com/5079556/194765090-50af8312-a0ca-4722-906a-2b031c84f38b.png">

**Comment by rjschof** [comment]
> I think this may have been fixed by https://github.com/ruby/irb/pull/379
> 
> 
> 
> <img width="252" alt="截圖 2022-10-09 16 22 48" src="https://user-images.githubusercontent.com/5079556/194765090-50af8312-a0ca-4722-906a-2b031c84f38b.png">
> 
> 

Thank you for the heads up!
