### ISSUE TITLE
Copy&Paste code with TAB symbol inserts `source` into the code which makes it `void value expression`

### ISSUE THREAD

**Issue by vimutter** [ruby/irb#382]
## Description

IRB Copy&Pasting code with TAB symbol inserts `source` into the code which makes it `void value expression`.

Essentially if you want to quick test run some code from editor which contains TAB, code inserted gets altered which makes it invalid.

Test code 

```
def test
  loop do
  	break # Here is <space><space><tab>break
  end
end
```

If you paste it gets entered as:
 
```
def test
  loop do
source break 
  end
end
```

## Result of irb_info
```
Ruby version: 3.1.1
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.0
.irbrc path: /home/user/.rvm/rubies/ruby-3.1.1/.irbrc
RUBY_PLATFORM: x86_64-linux
LANG env: C.UTF-8
East Asian Ambiguous Width: 1
```

**Comment by tompng** [comment]
IRB 1.11.1 https://github.com/ruby/irb/pull/832 fixed not to autocomplete on the beginning of the line.
Reline 0.5.6 https://github.com/ruby/reline/pull/655 supported bracketed paste. Reline will insert TAB character(if terminal emulator supports bracketed paste feature).
