### ISSUE TITLE
Adding test cases on no rdoc gem case.

### ISSUE THREAD

**Issue by junaruga** [ruby/irb#396]
## Description

> What are your expected behavior and actual behavior of your environment?

On the latest master b24852058fc87c940252c8a711c60ae2eb298082, the rdoc is required as soft dependency (= load the `rdoc` when it is needed).

```
$ grep -ril rdoc lib/
lib/irb/cmd/help.rb
lib/irb/completion.rb
lib/irb/easter-egg.rb
lib/irb/input-method.rb
```

And this is useful. Because on Fedora project, there is `rubygem-irb` RPM package, and users can install the RPM without the rdoc gem. So, I want to see the test cases of no rdoc to prevent this kind of issue, https://github.com/ruby/irb/issues/342.

I think we can add the test cases by mocking `Kernel#require` with returning `LoadError` when the argument is `rdoc`. (ref: https://github.com/ruby/irb/pull/395#issue-1351284638)

When chatting on the Ruby Slack, I was told that the [test-unit-rr](https://rubygems.org/gems/test-unit-rr) gem could be used to implement the mock. 

And while the ruby/irb's test is also used in ruby/ruby, and ruby/ruby doesn't want to depend on the test-unit-rr, we can implement the new tests using a flog to check if the current running environment is ruby/irb or ruby/ruby by a flag like `ruby_core?` used in Bundler's test,  https://github.com/ruby/ruby/blob/d6f21b308bcff03e82f8b3dbf11a852ce111b3b3/spec/bundler/support/path.rb#L250-L259 .

## Result of irb_info

> Please paste the result of `irb_info` command in IRB.

As this ticket is about enhancing the tests, there is no information about this item.

## Terminal Emulator

> What's your terminal emulator?

As this ticket is about enhancing the tests, there is no information about this item.

## Setting Files

> Are you using `~/.irbrc` and `~/.inputrc`?

As this ticket is about enhancing the tests, there is no information about this item.

**Comment by st0012** [comment]
FYI, I have added tests for all `rdoc` requires except the one in `easter-egg.rb` with:

- https://github.com/ruby/irb/pull/421
- https://github.com/ruby/irb/pull/418
- https://github.com/ruby/irb/pull/416

**Comment by junaruga** [comment]
Thanks! Great work!

**Comment by hsbt** [comment]
@junaruga Can we close this?

**Comment by junaruga** [comment]
Thanks, that's excellent work!
It seems that there are tests for the `lib/irb/cmd/help.rb`, `lib/irb/completion.rb` and `lib/irb/input-method.rb` on the latest master branch. But I couldn't find a test for the `lib/irb/easter-egg.rb`. Do we have the test for the file?

```
$ grep -r without_rdoc test/
test/irb/helper.rb:    def without_rdoc(&block)
test/irb/test_cmd.rb:    def test_help_without_rdoc
test/irb/test_cmd.rb:      out, _ = without_rdoc do
test/irb/test_completion.rb:      def test_perfect_matching_stops_without_rdoc
test/irb/test_completion.rb:          without_rdoc do
test/irb/test_input_method.rb:    def test_initialization_with_use_autocomplete_but_without_rdoc
test/irb/test_input_method.rb:      without_rdoc do
```

**Comment by junaruga** [comment]
> FYI, I have added tests for all rdoc requires except the one in easter-egg.rb with:

Sorry, it was mentioned. We don't need to have a test for the `easter-egg.rb`?

**Comment by junaruga** [comment]
Seeing the test source code again, there is no test for the `easter_egg` methods. When we add the test, we can add the non-rdoc case. And so, I think we can close this ticket. Thanks.

**Comment by st0012** [comment]
@junaruga The reason I didn't test `easter_egg`, with or without `rdoc`, is because it opens a pager and its implementation is not easily mock/stubable:

https://github.com/ruby/irb/blob/750cf4c4801bdf0059bca1503eb8e15ebce73473/lib/irb/easter-egg.rb#L107-L109

So I couldn't think of a way to test it without changing the implementation at the same time.

As a side note, `IRB::InputCompletor::PerfectMatchedProc` also uses `rdoc` pager. But because it stores the driver in a constant, we can switch to stdout during testing.

https://github.com/ruby/irb/blob/750cf4c4801bdf0059bca1503eb8e15ebce73473/test/irb/test_completion.rb#L216-L223
