### ISSUE TITLE
irb does not print result for assignments

### ISSUE THREAD

**Issue by hanazuki** [ruby/irb#40]
Expected behavior: When an assignment expression is entered, irb prints its value.
Actual behavior: Nothing is printed.

```
% ruby -v
ruby 2.7.0dev (2019-11-07T14:33:45Z master d62abc47c8) [x86_64-linux]
% bundle exec exe/irb -f
irb(main):001:0> a=1
irb(main):002:0>

% ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
% irb -f
irb(main):001:0> a=1
=> 1
irb(main):002:0>
```

**Comment by hanazuki** [comment]
This seems to be a intended change #12

**Comment by kj** [comment]
I personally think it's a little confusing and inconsistent. Assignments are expressions in Ruby, and return a value, so I'd expect irb to print that just like any other expression. It was a bit jarring when this suddenly changed. I had to ask myself 'wait, this does return a value right?'.
