### ISSUE TITLE
Home/End keys on numpad don't move cursor

### ISSUE THREAD

**Issue by LAC-Tech** [ruby/irb#408]
## Description

I have "Home" and "End" keys **on my numpad.**
I want to use them to navigate to the beginning and end of the line respectively:
Instead it prints out `^[[1~` and `^[[4~`.

I don't think it's a problem with my setup. these numpad Home/End keys work on the following interpreters on this system

- python
- node
- deno
- ocaml (with rlwrap)

`rlwrap irb` produces the same results for me as above.

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

ex.)

```
irb(main):001:0> irb_info
=>
Ruby version: 3.1.2
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.0 and /home/lewis/.inputrc
RUBY_PLATFORM: x86_64-linux
LANG env: en_NZ.utf8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

Alacritty. Same issue on XTerm and UXTerm.

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

no

**Comment by sshock** [comment]
Possibly related: https://github.com/ruby/irb/issues/330#issuecomment-1059906088

However, in your particular case, you may have additional problems because I use Alacritty as well and its terminfo is similar to XTerm.  With both Alacritty and XTerm, Home and End (both the normal ones and the ones on the keypad when numlock is not on) should not be sending `^[[1~` and `^[[4~` but rather `^[[H` and `^[[F` (or `^[OH` and `^[OF` when in application mode).

**Comment by LAC-Tech** [comment]
Are you familiar with reline? I had a brief poke around the source code but couldn't figure out where I might make this change.

**Comment by sshock** [comment]
> Are you familiar with reline? I had a brief poke around the source code but couldn't figure out where I might make this change.

What are you wanting to change?  Multiple PRs already exist to fix several issues with the keys not working properly:
* https://github.com/ruby/reline/pull/433
* https://github.com/ruby/reline/pull/462
* https://github.com/ruby/reline/pull/434

**Comment by LAC-Tech** [comment]
There's 5 other interpreters (haskell, python, node, deno, ocaml) on this system that handle my home and end keys just fine. It's a little bit hard for me to imagine they all have extensive workarounds for my "weird" setup. It feels a lot more like reline is doing something brittle.

But if there's a handful of PRs around this issue already, me adding another is unlikely to help, so I appreciate the context around this.

Here's the `showkey -a` for Home and End.

```
^[[H 	 27 0033 0x1b
 	 91 0133 0x5b
 	 72 0110 0x48
^[[F 	 27 0033 0x1b
 	 91 0133 0x5b
 	 70 0106 0x46
```

**Comment by sshock** [comment]
Oh, good.  Your Home and End are actually sending what they are supposed to.

So yeah, either one of https://github.com/ruby/reline/pull/433 or https://github.com/ruby/reline/pull/462 would fix your problem.

In the meantime, you can try [this workaround](https://github.com/ruby/irb/issues/330#issuecomment-1250387963) or any of the other workarounds mentioned in that issue.

**Comment by st0012** [comment]
I think this has been addressed by https://github.com/ruby/reline/pull/569? cc @tompng

**Comment by LAC-Tech** [comment]
This will fix will be in an upcoming irb release?

Not sure what you mean by python3 not handling home and end. I am typing it in the python interpreter right now (3.11.5) and it works absolutely fine. Where as irb (1.6.2) gives me:

```
^[[H^[[F               
```

**Comment by st0012** [comment]
@LAC-Tech The issue has been fixed and released in Reline, so the issue should be gone once you upgraded it. But I'd recommend upgrading to the latest Reline + IRB with `gem install irb`.

**Comment by LAC-Tech** [comment]
Thanks so much! works great now.
