### ISSUE TITLE
Remove tracer and e2mmap dependencies

### ISSUE THREAD

**Issue by hsbt** [ruby/irb#42]
This is a reminder issue.

**Comment by aycabta** [comment]
Ref. https://github.com/ruby/irb/commit/cb50fa3738121e4d829cb05b4bcb0d5fb43760c5, https://github.com/ruby/irb/commit/02fefe19ae3d7647584959f7124f53acc62fd3cf, https://github.com/ruby/irb/commit/13072394459f6bc3f8548ca212dbca3e79d923ef, https://github.com/ruby/irb/commit/ba8bce8d25050e4af6b036a5075e50ffc3c7dbde.
