### ISSUE TITLE
Cannot paste in 53 lines

### ISSUE THREAD

**Issue by schneems** [ruby/irb#46]
When I try pasting in this code, it is extremely slow on my machine and stops around line 37:

```
require 'thread'

def fib( n )
  return  n  if ( 0..1 ).include? n
  ( fib( n - 1 ) + fib( n - 2 ) )
end

thread_execution_time = Hash.new {|h, k| h[k] = [] }
mutex = Mutex.new
cv = ConditionVariable.new

execution_time = []
thread_count = 1
work_count = 512

(1..128).each do |thread_count|
  sequential_work = Array.new(work_count, 20)
  mutex.lock
  threads = []
  thread_count.times.each do
    threads << Thread.new do
      begin
        loop do
          mutex.synchronize do
            #cv.wait(mutex)
            if sequential_work.any?
              fib(sequential_work.pop)
            else
              # No work to do, exit!
              Thread.exit
            end
          end
        end
      rescue Exception
        STDERR.puts "Error: #{$!.inspect}"
        raise
      end
    end
  end
  sleep 0.1
  puts "Working #{work_count} with #{thread_count} threads"
  last = Time.now
  mutex.unlock
  #cv.broadcast()
  threads.each { |t| t.join }
  execution_time[thread_count] = Time.now - last
end

execution_time.each_with_index do |x, i|
  puts "#{i}, #{x}"
end
```

Using:

```
$ gem list | grep irb
irb (1.2.0, default: 1.0.0)
⛄ 2.6.5 🚀  ~/Documents/projects/ruby (trunk)
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
```

**Comment by mame** [comment]
It reproduces with xterm; it stops around line 26.  It does not reproduce with terminator.  What terminal emulator are you using?

**Comment by mame** [comment]
Ahh, I guess the issue depends upon the height of the terminal.

**Comment by schneems** [comment]
I am using iterm2 as my terminal. My widow height is currently 68 lines

**Comment by tfreedman** [comment]
I've managed to reproduce this as well (iTerm2 on 10.14), except for me it alternates between pasting very slowly one character at a time or crashing IRB entirely (and trying to run the paste commands in bash, which is super dangerous). This currently makes Ruby 2.7 completely useless for me, as I can't easily change the IRB version back to 0.9.6 and can't use any 2.7 consoles.

**Comment by ima1zumi** [comment]
The current version did not reproduce the problem, so it is closed. If the problem is still occurring, please reopen.
