### ISSUE TITLE
Value is not output after assignment

### ISSUE THREAD

**Issue by schneems** [ruby/irb#48]
If I paste this code into IRB then I get no output from the last line:

```
def fib( n )
  return  n  if ( 0..1 ).include? n
  ( fib( n - 1 ) + fib( n - 2 ) )
end

var = fib(20)
```
It makes it look like the calcualtion did not succeed or there was no value. To get an output I need:

```
def fib( n )
  return  n  if ( 0..1 ).include? n
  ( fib( n - 1 ) + fib( n - 2 ) )
end

var = fib(20)
var
```

This is confusing and diverges from previous behavior.

```
$ gem list | grep irb
irb (1.2.0, default: 1.0.0)
⛄ 2.6.5 🚀  ~/Documents/projects/ruby (trunk)
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
```

**Comment by mame** [comment]
You may know, it is an intentional change.  When the output is huge (e.g., `v = [*0..10000]`), it flushes the terminal log.

Suppressing the output of an assignment is useful.  But it may bring a surprise to those who are familiar with the old behavior.  It is a trade-off.  Do you prefer no-suppression by default?

**Comment by schneems** [comment]
BTW thank you for triaging and responding to all of my reports I appreciate your time and help!

> You may know, it is an intentional change. When the output is huge (e.g., v = [*0..10000]), it flushes the terminal log.

I considered it was an intentional change, but did not know the context. Thank you for the extra information. I didn't know the intent of the decision.


> Suppressing the output of an assignment is useful. But it may bring a surprise to those who are familiar with the old behavior. It is a trade-off. Do you prefer no-suppression by default?

I agree that for large outputs it is helpful to not display them, in IRB i would use a trick like:

```
v = [*0..10000]; nil
```

But it would be nice to not need that. Would it be possible to conditionally output the values if they could fit inside of the existing window? It might be a little confusing that sometimes values are output and sometimes they are not, but I do like that when I am typing displaying the results for short outputs does save me time and typing.

I think there might be room for some different behavior (like proposed here, with conditionally not showing output if it is over some threshold). If that's not possible though, I think my personal preference would be to have no-suppression by default.

**Comment by pimpin** [comment]
I'm also surprised by this "new" behaviour. I would expect at least a representation of the returned object with his class name and his object id. This expectation comes from my Rails console habits which I use most of the time.

Notice that you can also use the `_` variable to output your value before assigning it. You still need one extra line to print and assign. But you could stop before assignment in case of unexpected value.

```ruby
def fib( n )
  return  n  if ( 0..1 ).include? n
  ( fib( n - 1 ) + fib( n - 2 ) )
end

fib(20)
var = _
```

**Comment by onlynone** [comment]
In case you didn't see it, you can get the old behavior by setting `IRB.conf[:ECHO_ON_ASSIGNMENT] = true` in your `~/.irbrc`.

**Comment by st0012** [comment]
The current default is to echo assignment with truncation:

https://github.com/ruby/irb/blob/4b7dcdf66f198e6c23f49003f18d39cc345e45f2/lib/irb/context.rb#L140-L141

And I think the case in description is now working as expected: 

![Screenshot 2023-10-25 at 20 58 45](https://github.com/ruby/irb/assets/5079556/c7ff64fe-a2a1-41be-a7a3-4a14fddfa522)

So I'm closing this now.
