### ISSUE TITLE
IRB 1.2.0 broken on a Heroku private space

### ISSUE THREAD

**Issue by schneems** [ruby/irb#50]
```
$ heroku run bash -a schneems-my-space-app --size=private-s
~ $ bundle exec irb -v
irb 1.2.0 (2019-12-07)
~ $ bundle exec irb
This version of IRB is drastically different from the previous version.
If you hit any issues, you can use "irb --legacy" to run the old version.
If you want to just erase this message, please use "irb --multiline" or
add `IRB.conf[:USE_MULTILINE] = true` to your ~/.irbrc file.
bundler: failed to load command: irb (/app/vendor/bundle/ruby/2.5.0/bin/irb)
ZeroDivisionError: divided by 0
  /app/vendor/bundle/ruby/2.5.0/gems/reline-0.0.7/lib/reline/line_editor.rb:208:in `div'
  /app/vendor/bundle/ruby/2.5.0/gems/reline-0.0.7/lib/reline/line_editor.rb:208:in `calculate_height_by_width'
  /app/vendor/bundle/ruby/2.5.0/gems/reline-0.0.7/lib/reline/line_editor.rb:349:in `rerender'
  /app/vendor/bundle/ruby/2.5.0/gems/reline-0.0.7/lib/reline.rb:210:in `inner_readline'
  /app/vendor/bundle/ruby/2.5.0/gems/reline-0.0.7/lib/reline.rb:160:in `readmultiline'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/input-method.rb:258:in `gets'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:517:in `block (2 levels) in eval_input'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:693:in `signal_status'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:516:in `block in eval_input'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:166:in `lex'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:138:in `block (2 levels) in each_top_level_statement'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:135:in `loop'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:135:in `block in each_top_level_statement'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:134:in `catch'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb/ruby-lex.rb:134:in `each_top_level_statement'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:535:in `eval_input'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:470:in `block in run'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:469:in `catch'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:469:in `run'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/lib/irb.rb:398:in `start'
  /app/vendor/bundle/ruby/2.5.0/gems/irb-1.2.0/exe/irb:11:in `<top (required)>'
  /app/vendor/bundle/ruby/2.5.0/bin/irb:23:in `load'
  /app/vendor/bundle/ruby/2.5.0/bin/irb:23:in `<top (required)>'
~ $ ~ $ ~ $ ~ $ ~ $ ~ $ ~ $ ~ $ ~ $ ~ $ ~ $
```

You can email me richard@heroku.com and I can give a collaborator access to the app for debugging.

If you run it with `irb --legacy` it works fine.

Internal ticket for Heroku ID 800955

**Comment by zunda** [comment]
This is basically Heroku setting terminal size unexpectedly. I have asked the engineers to see if Heroku maybe able to fix this. On the other hand, I also expect that the code is more resilient to such misconfigurations with maybe guarding the code on `irb` or `reline` from zero-window widths.

```
$ heroku run bash -a <private-space-app>
~ $ stty size
0 0
~ $ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
~ $ ruby -rio/console -e 'p STDIN.winsize'
[0, 0]
```

**Comment by mame** [comment]
Now I've tried and it works perfectly.  Did you fix the Heroku side?

![image](https://user-images.githubusercontent.com/21557/71538703-bfda8080-2972-11ea-954b-f9056e0420be.png)

If there are many environments where IRB cannot get the terminal size, it would be great if IRB works under the environment, for example, by degenerating the mode to `--legacy` automatically.

**Comment by zunda** [comment]
Thanks for looking into this! The problem actually only surfaces on one-off dynos in Private Spaces where many platform components are different from those for Common Runtime. I've just checked the problem still occurs in a Private Space like Richard posted.

For Private Space users, one of the following would be able to work this around.

(1) Create a config file for IRB to disable the multiline feature

```sh
$ echo 'IRB.conf[:USE_MULTILINE] = false' > .irbrc
$ git add .irbrc
$ git commit -m 'Disable multiline on IRB to avoid error in Private Spaces'
$ git push heroku master
```

(2) Specify the `--legacy` command line option

```sh
$ heroku run bash
~ $ irb --legacy
```

(3) Run the `reset` command to correct the terminal size

```
$ heroku run bash
~ $ reset
~ $ irb
```

**Comment by mame** [comment]
I see.  I'm curious whether other terminal applications like vim, emacs, and less work correctly on the environment.  If they work, IRB may get the terminal size in any other way.

**Comment by aycabta** [comment]
Maybe, this is fixed by https://github.com/ruby/reline/pull/98.

**Comment by zunda** [comment]
Thank you! I confirmed ruby/reline#98 made it possible to run IRB in a Private Space. However, it seems that we'd need to wait for another release of Ruby. For now, I could force IRB to use reline at master with specifying it in `Gemfile` and removing the bundled version.


```
$ heroku run bash
~ $ stty size
0 0
$ grep reline Gemfile
gem 'reline', git: 'https://github.com/ruby/reline'
~ $ find . -name ansi.rb
./vendor/ruby-2.7.0/lib/ruby/2.7.0/reline/ansi.rb
./vendor/bundle/ruby/2.7.0/bundler/gems/reline-e498a9a4e75c/lib/reline/ansi.rb
~ $ rm -r ./vendor/ruby-2.7.0/lib/ruby/2.7.0/reline*
~ $ RUBYOPT='-I ./vendor/bundle/ruby/2.7.0/bundler/gems/reline-e498a9a4e75c/lib' irb
irb(main):001:0> 
```

**Comment by schneems** [comment]
> need to wait for another release of Ruby.

IRB can be released independently from Ruby now, which means we won't have to wait as long if this can be rolled into a release sooner.

As a short term fix. A customer of heroku who is blocked by this can point to github in their gemfile:

```ruby
gem 'irb', github: 'ruby/irb'
```

> Note: I think this works, but i've not actually tried it. Not sure if there's an edge case with "default gems" that would prevent/impact this

**Comment by zunda** [comment]
Thanks but unfortunately, the reline gem installed by default with ruby-2.7.0 needs to be removed for the fix to work. Good news is that a fix on Heroku is ready to be deployed in the next upgrade of Private Spaces.

**Comment by zunda** [comment]
For Heroku Private Space users, a fix on the Private Space side has been deployed. Please try enabling the multi line feature and enjoy it.
