### ISSUE TITLE
Update `MagicFile` to use `require`

### ISSUE THREAD

**Issue by nirvdrum** [ruby/irb#530]
## Description

IRB's `MagicFile` reimplements `require` by doing an explicit `File#read` and `eval` over the processed string. The code is a bit difficult to understand and it's not immediately clear why `require` can't be used.

The use of POSIX calls introduces some complications for non-CRuby implementations. In TruffleRuby, for instance, we can optimize `require` in ways that are not possible with a chained series of `IO` calls. I'm pretty sure this is true of JRuby as well.

Moreover, with `require` we can better control where the file contents live. E.g., TruffleRuby's core library can be persisted inside of a native image, much like Smalltalk snapshots, by loading the file contents into memory before the image is created. It'd be great if we could do the same for Ruby's standard library, but IRB presents difficulties because it reads explicitly from the filesystem. Without introducing a virtual filesystem or patching IRB in TruffleRuby, there's no way for us to load IRB magic files from a native image.

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

ex.)

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.1                            
IRB version: irb 1.6.2 (2022-12-13)            
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: arm64-darwin22                  
LANG env: en_US.UTF-8                          
East Asian Ambiguous Width: 1  
```

**Comment by eregon** [comment]
Where do you see the `require` override in IRB? I couldn't find it.

What I remember is a long time ago we found that IRB was doing something like `File.read(__FILE__)` to find the filesystem/locale encoding IIRC, and that meant, that specific IRB file must be a real file and cannot be e.g., cached in the TruffleRuby Native Image. I don't find such code in IRB anymore, maybe it was removed.

**Comment by eregon** [comment]
So to clarify what's important is that files in the irb stdlib/gem are loaded using `require` rather than File.read or so, so then we could store those files in a `.jar` and/or cache their AST/bytecode/etc and don't need to also have the files available on the filesystem.
This is also a necessary condition for stdlib if e.g. we want to produce a single executable containing core, stdlib and the user program.

**Comment by nirvdrum** [comment]
`require` isn't being overridden. Apologies for the confusion around "reimplemented". I meant it's being implemented from scratch by `MagicFile` and its callers. It opens a Ruby source file, scans it for a shebang, looks for the file's encoding, updates the IO object's encodings, reads out the Ruby source code, and then calls `eval` on it. It's not exactly the same as `require`, but it's pretty close.

**Comment by eregon** [comment]
Right, it'd be nice to remove that logic if it can be replaced by `require` or `load`.
I'd be interested to see a list of files loaded by MagicFile to have an idea which files are loaded that way by IRB.

**Comment by st0012** [comment]
Once #571 and #573 are merged, `MagicFile` won't be used to read internal files anymore, which should unblock the snapshot image build?

**Comment by st0012** [comment]
Since both of the above PRs have been merged and no more internal files are loaded through `MagicFile`, I'm closing this now.
As a follow up I also created #574 to complete "retire" `MagicFile`, but I think you can try building native image with the current master already.
