### ISSUE TITLE
Support autocomplete for methods?

### ISSUE THREAD

**Issue by utkarsh2102** [ruby/irb#54]
Hi,

Thanks for the amazing work y'all have put in here.
Just a step further, can autocompletion be supported for methods (at least, in-built)?
Like Python supports autocompletion that often helps speed up things (and more).

Can we expect this sooner or later?

**Comment by SqREL** [comment]
Hi @utkarsh2102 
Doesn't `tab` work for you?

**Comment by utkarsh2102** [comment]
Hi @SqREL,
Not like I'd expect it to be :/
At least not the methods..

**Comment by SqREL** [comment]
@utkarsh2102 Could you elaborate on this? What are your expectations?

Just to be on the safe side, we are talking about `1.2.1` version, right?

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/reline/pull/318 and https://github.com/ruby/irb/commit/6258cc6b578be156db644bf8b86a82acc099da2b.

@utkarsh2102 Would you try it by `gem install irb --pre`?

**Comment by utkarsh2102** [comment]
> This is fixed by [ruby/reline#318](https://github.com/ruby/reline/pull/318) and [6258cc6](https://github.com/ruby/irb/commit/6258cc6b578be156db644bf8b86a82acc099da2b).

Yay, lovely! Thank you! 🎉 

> @utkarsh2102 Would you try it by `gem install irb --pre`?

Sure, shall do. Thanks, again! \o/
