### ISSUE TITLE
Crashes with complex autoindent

### ISSUE THREAD

**Issue by aycabta** [ruby/irb#55]
Reported by @mame:

```ruby
(((
)
)
```

[Reported at #16453](https://bugs.ruby-lang.org/issues/16453) by @JunichiIto

```ruby
[<<FOO]
hello
FOO
```

**Comment by BenKanouse** [comment]
I attempted to fix this issue here: https://github.com/ruby/irb/pull/56

Please let me know if you have any feedback.

Thanks!

**Comment by BenKanouse** [comment]
I believe that this PR fixes both issues: https://github.com/ruby/irb/pull/58

It also adds test for both issues. I'm looking forward to any feedback. Thanks!

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/irb/pull/58.

Thank you, @BenKanouse!
