### ISSUE TITLE
IRB dies with Errno::EPERM when it tries to expand `require`-ed features on directories without permissions

### ISSUE THREAD

**Issue by tagomoris** [ruby/irb#606]
## Description

To reproduce this, on macOS:

1. push my HOME (e.g., "/Users/tagomoris") to `$LOAD_PATH`
2. type `require 'something'`

and then got an error like this:
```
irb(main):002:0> require 'h<internal:dir>:220:in `glob': Operation not permitted - /Users/tagomoris/Library/Accounts (Errno::EPERM)
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:103:in `block in retrieve_files_to_require_from_load_path'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:101:in `each'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:101:in `each_with_object'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:101:in `retrieve_files_to_require_from_load_path'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:141:in `block in <module:InputCompletor>'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/irb/completion.rb:159:in `block in <module:InputCompletor>'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/reline/line_editor.rb:1691:in `call_completion_proc_with_checking_args'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/reline/line_editor.rb:545:in `call_completion_proc_with_checking_args'
        from /Users/tagomoris/.rbenv/versions/3.2.2/lib/ruby/3.2.0/reline.rb:234:in `block in <class:Core>'
(snip)
```

This is caused by a directory without read permission under the path added to `$LOAD_PATH`. The auto-complete feature of irb will try to expand the path eagerly & recursively, and then get a permission error `Errno::EPERM`.

My expected behavior is either:

* (A) Path expansion about `require` is done only for a single depth (without any '/')
  * and the 2nd depth expansion will be tried when '/' is typed
* (B) Path expansion ignores all `Errno::EPERM` and stops the recursive search at that directory

IMO all files in all subdirectories seems too aggressive to me. So I prefer the option (A), but (B) might be the simpler option and easy to implement.

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.2.2                            
IRB version: irb 1.6.2 (2022-12-13)            
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: arm64-darwin21                  
East Asian Ambiguous Width: 1                  
```

## Terminal Emulator

macOS Terminal

## Setting Files

No.

**Comment by tompng** [comment]
Maybe solved or improved in TypeCompletor(repl_type_completor 0.1.2), problem remains in RegexpCompletor

**Comment by tagomoris** [comment]
I tried the same operation on Ruby 3.3 w/ irb 1.11.0, and the problem was not reproduced either with or without `--type-completor`.
Thank you!
