### ISSUE TITLE
IRB doesn't save input history when exited with `exit!`

### ISSUE THREAD

**Issue by st0012** [ruby/irb#612]
Because IRB [relies on `IRB.conf[:AT_EXIT]` config](https://github.com/ruby/irb/blob/master/lib/irb/ext/save-history.rb#L55), which will be run in `at_exit`, to save a session's input history. When users exit the session with `exit!`, the input is not written.

### Reproduction Steps

1. Open an IRB session and run

    ```
    irb(main):001:0> a = 1
    => 1
    irb(main):002:0> b = 2
    => 2
    irb(main):003:0> exit
    ```
1. Open another session and type up-arrow to check the above history
1. In the same session, run
    
    ```
    irb(main):001:0> c = 3
    => 3
    irb(main):002:0> d = 4
    => 4
    irb(main):003:0> exit! # with a ! this time
    ```
1. Open another session and type up-arrow to view history

#### Expected Behaviour

Input from step 3 should be part of the history

#### Actual Behaviour

Input from step 3 is lost

**Comment by tompng** [comment]
This is the expected behavior of `Kernel.exit!`. Skips all at_exit handlers and ensure statements.
I think we can add `exit!` command that executes `Kernel.exit`

**Comment by tompng** [comment]
Just for my case, most of the time I use `exit!` is when I want to just Kernel.exit because exit is overridden in irb.
like
```ruby
loop{
  ...
  binding.irb # want to exit the program after debugging/investigating. don't want to skip cleanup (ensure, at_exit)
}
```
