### ISSUE TITLE
irb hangs when type `/\u{`

### ISSUE THREAD

**Issue by znz** [ruby/irb#620]
## Description

Expected: I can input `{` after `/\u`.
Actual: Do not show `{`, and irb hangs.

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.2
IRB version: irb 1.7.0 (2023-06-03)
InputMethod: RelineInputMethod with Reline 0.3.5
RUBY_PLATFORM: arm64-darwin22
LANG env: ja_JP.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

What's your terminal emulator?

Terminal.app

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

No.

**Comment by tompng** [comment]
It looks like a bug in ruby.
I reported to https://bugs.ruby-lang.org/issues/19750
