### ISSUE TITLE
irb stopped saving history since 1.7.2 on macOS M2 Pro Ventura 13.4.1

### ISSUE THREAD

**Issue by dexterouschen** [ruby/irb#641]
## Description

1.7.1 saves history for me just fine as part of rails console and standalone, 1.7.2 and 1.7.3 won't save history with or without `~/.irbrc` config

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

Ruby version: 3.1.3
IRB version: irb 1.7.3 (2023-07-12)
InputMethod: RelineInputMethod with Reline 0.3.6
.irbrc path: ~/.rvm/rubies/ruby-3.1.3/.irbrc
RUBY_PLATFORM: arm64-darwin21
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1

## Terminal Emulator

macOS zsh

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

No

**Comment by st0012** [comment]
@dexterouschen Thanks for reporting 👍 I've opened #642 to address it.
