### ISSUE TITLE
Running irb on debugger on irb dose not save the irb history

### ISSUE THREAD

**Issue by takatea** [ruby/irb#666]
## Description

Running irb on debugger on irb dose not save the irb history.

### To Reproduce

1. Prepare a Ruby script `~/path_to_test_rb/test.rb` like this:

   ```ruby
   require "debug"

   class Test
       def run
           debugger
       end
   end
   ```

2. Remove `~/.irb_history` and `~/.rdbg_history` files to clean up
3. Run irb (`irb#1`)
4. Require `~/path_to_test_rb/test.rb` on irb
5. Execute `Test.new.run` on irb
6. Debugger start
7. Execute the irb command on debug
8. Start the second irb (`irb#2`)
9. Quit `irb#2`
10. Execute the continue command on debug
11. Quit `irb#1`
12. Execute `ls ~/.irb_history  ~/.rdbg_history`

For example, my case is:

```ruby
$ irb
irb(main):001:0> require "./test"
=> true
irb(main):002:0> Test.new.run

[1, 7] in ~/path_to_test_rb/test.rb
     1| require "debug"
     2|
     3| class Test
     4|     def run
=>   5|         debugger
     6|     end
     7| end
=>#0    Test#run at ~/path_to_test_rb/test.rb:5
  #1    <top (required)> at (irb):2
  # and 18 frames (use `bt' command for all frames)
(ruby) puts :debugger
debugger
nil
(rdbg) irb    # command
irb(#<Test:0x000000010d472dc8>):001:0> puts :irb
irb
=> nil
irb(#<Test:0x000000010d472dc8>):002:0> quit
(rdbg) continue    # continue command
=> #<Test:0x000000010d472dc8>
$ ls ~/.irb_history  ~/.rdbg_history
```

### Actual Result

```sh
$ ls ~/.irb_history  ~/.rdbg_history
ls: /Users/username/.irb_history: No such file or directory
/Users/username/.rdbg_history
```

### Expected behavior

```sh
$ ls ~/.irb_history  ~/.rdbg_history
/Users/username/.irb_history
/Users/username/.rdbg_history
```

## Additional Info

I have tested the following cases:

**1. Running only irb**

- I got the expected result
  - `irb_history` was saved

**2. Running irb on debugger executed by `ruby -e 'require "debug"; debugger'`**

- I got the expected result
  - `irb_history` and `.rdbg_history` were saved

**3. Running debug on irb**

- I got the expected result
  - `irb_history` and `.rdbg_history` were saved

**4. Running irb on irb**

- I got the expected result
  - `irb_history` was saved

## Result of irb_info, and debug/rdbg version

```sh
$ irb
irb(main):001:0> irb_info
Ruby version: 3.3.0
IRB version: irb 1.7.4 (2023-07-15)
InputMethod: RelineInputMethod with Reline 0.3.6
RUBY_PLATFORM: x86_64-darwin22
LANG env: ja_JP.UTF-8
East Asian Ambiguous Width: 1

$ gem list | grep debug
debug (1.8.0)

$ rdbg -v
rdbg 1.8.0
```

## Terminal Emulator

```
iTerm2
Build 3.4.19
```

## Setting Files

No specific settings were applied.

## Additional Note

~This report is also planned to be submitted to [ruby/debug](https://github.com/ruby/debug).~
I have also reported this problem on ruby/debug#1009

And then,
I realized that this problem might be similar to #659 after making this report.

**Comment by st0012** [comment]
Thanks for the detailed report 👍 
Yes, it's caused by the same problem as #659 and I'm working on a solution for it. We're also aware that there's another history related issue: https://github.com/ruby/debug/issues/994. But it will need to be addressed separately.
