### ISSUE TITLE
Why is there no method to reprint the source within binding.irb?

### ISSUE THREAD

**Issue by olivierlacan** [ruby/irb#67]
## Description

When using `binding.irb`, the local source Ruby code is printed when the debugging session starts but if it's cleared there doesn't seem to be a method to reprint it.

```ruby
# irb_source.rb
def test
  binding.irb
end

test
```

```ruby
$ ruby irb_source.rb

From: irb_source_bug.rb @ line 2 :

    1: def test
 => 2:   binding.irb
    3: end
    4:
    5: test

irb(main):001:0>
```

Pry and byebug both offer a way to reprint the local source around the breakpoint without quitting the session. While it's understandable that `binding.irb` would have fewer features, this seems like an important one.

## Terminal Emulator

What's your terminal emulator? iTerm 2

**Comment by tompng** [comment]
Command `whereami` is added in https://github.com/ruby/irb/pull/204
