### ISSUE TITLE
Sorbet type error in IRB::ReadLineInputMethod

### ISSUE THREAD

**Issue by S-Aggarwal** [ruby/irb#723]
## Description

We are getting a new Sorbet type error with version 1.8.1 which we didn't get in 1.7.4. 

![image](https://github.com/ruby/irb/assets/24316351/dd23fa9b-169f-41ad-b3c0-54a15ab36b68)

We use `bundler`, `sorbet` and `tapioca` in our project. To repro, do
- Add `irb 1.8.1` as a dependency to Gemfile and run `bundle install`
- Run `bin/tapioca gems` to generate RBI files for the dependency
- Run `bundle exec src tc` to run Sorbet type-checking which produces above error.

## Result of irb_info

```
irb(main):001> irb_info
Ruby version: 3.2.2
IRB version: irb 1.8.1 (2023-09-04)
InputMethod: RelineInputMethod with Reline 0.3.8
.irbrc path: /Users/shubham/projects/backend/.irbrc
RUBY_PLATFORM: arm64-darwin22
East Asian Ambiguous Width: 1
```

## Terminal Emulator

I am using the terminal emulator inside RubyMine on MacOS but the error should be agnostic.

## Setting Files
My `.irbrc`
```
IRB.conf[:USE_AUTOCOMPLETE] = false
```

**Comment by jesse-shopify** [comment]
Are you using irb for only debugging? If nothing in your code depends on it then you can add it to tapioca exclude. That's what I've been doing.

**Comment by S-Aggarwal** [comment]
Yeah we're only using it for debugging. We've just pinned ours to 1.7.4 to mitigate for now.

**Comment by st0012** [comment]
You can workaround it by updating `sorbet/tapioca/config.yml` to

```
gem:
  exclude:
  - irb
```

and run `bundle exec tapioca gem irb`.

**Comment by st0012** [comment]
And I'm closing this now as there's nothing we can do to fix it from the IRB side.
