### ISSUE TITLE
Autocomplete Color Customization?

### ISSUE THREAD

**Issue by thewatts** [ruby/irb#724]
## Description

Honestly, (and maybe this is just me) - but for whatever reason the color schemes I use and the autocomplete with IRB simply do not mix (note: I'm partially colorblind - so again, perhaps just me).

It's what has kept me going back to pry.

I've tried both Darkula, and Catppuccin (current)

Here's a screenshot:

<img width="562" alt="image" src="https://github.com/ruby/irb/assets/1141717/f3077405-ab00-4e29-85fa-f25191103554">

---

*My question: *Is there a way to customize the colors used by the autocomplete?*

---

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.0
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: arm64-darwin22
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

[iTerm](https://iterm2.com), but also apparent in Terminal.app (MacOSX)

## Setting Files

Not using any custom setting files

---

Many thanks!

**Comment by st0012** [comment]
Hi @thewatts, thanks for raising this. We’re aware of the problem and have started a discussion on introducing related APIs for customization in Reline (the gem that powers autocomplete dialog): https://github.com/ruby/reline/pull/552

**Comment by thewatts** [comment]
Thanks for the quick response, @st0012!

I appreciate you!

**Comment by st0012** [comment]
I'm closing this as the Reline feature has been pretty stable and there are even themes like https://github.com/vitallium/irb-theme-tokyonight
