### ISSUE TITLE
basic usability

### ISSUE THREAD

**Issue by zenspider** [ruby/irb#775]
I'm having so many problems with irb. Basic usability issues. For example, if your config includes:

```
IRB.conf[:PROMPT_MODE] = :SIMPLE
```

and you type `help`, you literally can't tell that you've just entered `ri` mode. 

- [x] `help` should help. 

- [x] `ri` should `ri`. 
`show_doc` just shouldn't be.

- [x] `cwws` and `chws` are _terribly_ named. 
Consider `cd` and... I dunno, `pwd`?

- [x] `chws` doesn't accept `..` and I can't figure out how to get out.

`chws` doesn't accept `-h`. 

- [x] `show_cmds` doesn't detail anything. There's no way to see help for a command.

- [x] `show_cmds` doesn't show any of the aliases.

- [x] `show_source` doesn't seem to be able to find ANY source for anything defined in the irb session.

That's 10 minutes worth of investigation prompted by @st0012 saying this thing was ready and should go in our Gemfiles. _I just don't think it is ready_. I used to LOVE irb and resisted using pry for years, but ever since the irb overhaul, I have found it to be very unusable.

Please sit down with someone unfamiliar with `irb` and watch them fire it up and try to use it. **Every** friction point, **every** confusion, **every** broken expectation should be written up as an issue, prioritized, and fixed.

**Comment by st0012** [comment]
Except that there's no plan (nor against) to accept `-h` argument for commands (as users can already do `help [cmd]`), I think all other problems mentioned here have been addressed. Thanks again for the feedback 🙂 
Please open new issues if you have other ideas 😄
