### ISSUE TITLE
Repurpose `help` command to show help messages

### ISSUE THREAD

**Issue by st0012** [ruby/irb#787]
We have been printing the deprecation message for `help` for a while:

```
[Deprecation] The `help` command will be repurposed to display command help in the future.
For RI document lookup, please use the `show_doc` command instead.
For command help, please use `show_cmds` for now.
```

For users installing IRB as a gem, they should have been exposed to the warning for a while. However, for users using the bundled IRB, they likely haven't seen it yet.

As a result, we should at least wait for Ruby 3.3 is released to make this change.

Addresses one of the points in #775

**Comment by nunosilva800** [comment]
Agreed. I think we can now repurpose `help` to do what people expect it to do. `show_cmds` is just not intuitive.
