### ISSUE TITLE
Ctrl-Y (yank) no longer works after statement entry

### ISSUE THREAD

**Issue by kozinski** [ruby/irb#85]
## Description

After killing a line (or part of a line) with Ctrl-K, it is normally retained and can be recalled with Ctrl-Y. Since Ruby 2.7.0, the kill buffer is cleared after a command is entered and Ctrl-Y does nothing.

Note that this only happens when a complete statement is entered (whether syntactically valid or not). When editing or adding to a multiline expression (such as a block or conditional body) the kill buffer is retained until either replaced or the entire statement is evaluated (or rejected with a SyntaxError).

## Steps to reproduce

1. Type any statement, such as `a = 5`, but don't press enter
2. Press Ctrl-A to go to the head of the line, then Ctrl-K to kill the entire line
3. Type any statement and press enter, or just press enter on the blank line
4. Press Ctrl-Y

### Expected result

`a = 5` is placed on the command line.

### Actual result

Nothing happens.

## Terminal Emulator

iTerm2 MacOS

**Comment by znz** [comment]
I can reproduce it.
And I think a following patch (for <https://github.com/ruby/ruby>'s master) is solved it.

```diff
diff --git a/lib/reline/line_editor.rb b/lib/reline/line_editor.rb
index 478d1d73f3..8ac0eefb25 100644
--- a/lib/reline/line_editor.rb
+++ b/lib/reline/line_editor.rb
@@ -148,7 +148,7 @@ def reset_variables(prompt = '', encoding:)
     @cleared = false
     @rerender_all = false
     @history_pointer = nil
-    @kill_ring = Reline::KillRing.new
+    @kill_ring ||= Reline::KillRing.new
     @vi_clipboard = ''
     @vi_arg = nil
     @waiting_proc = nil
```

**Comment by kozinski** [comment]
That does seem to fix the issue! So if the problem is not with IRB but with Ruby itself, then how can the fix be submitted there?
