### ISSUE TITLE
`->{}` makes prompt `irb(main):001:->`

### ISSUE THREAD

**Issue by znz** [ruby/irb#90]
## Description

After type`->{}`

Actual:
prompt is `irb(main):001:->`

Expected:
prompt is `irb(main):001:0>`

## Terminal Emulator

iTerm2

**Comment by SteveRedka** [comment]
What version is this?

I think in current version indentation is done with whitespaces - at least I don't see indentation indicator at all:

```ruby
2.6.3 :001 > class Foo
2.6.3 :002 >   def bar
2.6.3 :003 >   ...
