### ISSUE TITLE
Slow and odd behavior when using arrow left/right and option as meta key

### ISSUE THREAD

**Issue by olivierlacan** [ruby/irb#91]
## Description

When attempting to move the cursor in a binding.irb session, I expect no delay and for the cursor to move seamlessly.

## Terminal Emulator

What's your terminal emulator? **bash**
Ruby version: 2.7.0

## Demo

![Screen Recording 2020-03-21 at 03 22](https://user-images.githubusercontent.com/65950/77221862-26aba800-6b24-11ea-859f-229448472e3a.gif)

As you can see in the GIF above, the feedback cycle between key input (left/right arrow or left/right arrow + option) is regularly extremely slow, displaying control characters or blank spaces on top of code instead of simply moving the cursor.

The cursor routinely gets stuck on a specific character and the only way to solve the problem is to hit the `Enter` key and try again on a newline.

**Comment by nobu** [comment]
`bash` is a shell (command interpreter), but not a terminal emulator.
You will be able to see what terminal emulator you are using, by "about ..." menu.

**Comment by olivierlacan** [comment]
iTerm 2 for macOS. Long week. My bad.

**Comment by aycabta** [comment]
I tried but couldn't reproduce it. I think "left/right arrow + option as meta key" are not bound any GNU Readline event by default. Does your system have /etc/inputrc and ~/.inputrc?

**Comment by olivierlacan** [comment]
@aycabta Yes: 

```
$ cat ~/.inputrc
"\e[1;9D": backward-word
"\e[1;9C": forward-word
```

**Comment by olivierlacan** [comment]
Try up and down arrows but press as quickly as you can.  

![](https://d3vv6lp55qjaqc.cloudfront.net/items/340G0v1J3K1I0S3B1y3c/Screen%20Recording%202020-03-31%20at%2023.42.gif)

The worst part is that these artifacts often end up breaking IRB entirely because it acts as if code needs to be entered to close a block or a method definition. No output works and often indentation increases indefinitely on each new line Enter-ed. 

`exit` stops working as well and `control` + `c` throws a ` ERROR RubyLex::TerminateLineInput` exception: 

```
irb(#<Rack::Builder:0x00007faad013c158>):019:4* ^C^C
[2020-03-31 23:45:07] ERROR RubyLex::TerminateLineInput: Terminate Line Input\n\t/Users/olivierlacan/.rbenv/versions/2.7.0/lib/ruby/2.7.0/irb.rb:674:in `signal_handle'
```
