### ISSUE TITLE
Recalling command history no longer works in 2.7.0

### ISSUE THREAD

**Issue by JonRowe** [ruby/irb#94]
Prior to `2.7.0` the default version of `irb` allowed you to recall command history by pressing the up arrow. Now this seems to be disabled, weirdly it seems to be saving command history, just not allowing recall. If I switch to `irb --legacy` the recall is enabled and I can press "up" to recall commands entered in previous sessions without the `--legacy` flag.

Ruby: 2.7.0
IRB: 1.2.1 (2019-12-24)
OS:  Mac OS Catalina
Terminal: iTerm2 Build 3.3.10

**Comment by aycabta** [comment]
Would you install the latest version by `gem install irb reline` and try again?

**Comment by JonRowe** [comment]
My apologies I thought this was the latest released version. Same with:
```
irb 1.2.3
reline 0.1.3
```

**Comment by aycabta** [comment]
I can't reproduce what you reported. Could you copy and paste your complete reproducible log including outputs of IRB?

**Comment by JonRowe** [comment]
Starting a new irb session from my home directory:
```shell
Last login: Mon Mar 30 09:38:48 on ttys011
➜  ~ irb
2.7.0 :001 > Dir['*']
 => ["Music", "Pictures", "Code", "Talks", "Desktop", "Library", "Documents", "Downloads"]
2.7.0 :002 >
```
Pressing the up arrow key produces no further output, I would expect it to show `Dir['*']`.

**Comment by JonRowe** [comment]
The following (in the same shell) allows history:
```shell
2.7.0 :002 > exit
➜  ~ irb --legacy
2.7.0 :001 > 
```

**Comment by JonRowe** [comment]
![demo](https://user-images.githubusercontent.com/162976/77904949-532a9700-727d-11ea-8fc2-8eabefd90470.gif)

**Comment by JonRowe** [comment]
If I can provide anything more to help reproduce this let me know because its driving me up the wall!

**Comment by aycabta** [comment]
Hmm...I tried to reproduce with other Ruby committers on macOS with iTerm2 but I couldn't. Are you using .irbrc and .inputrc?

**Comment by JonRowe** [comment]
`.irb-history` is recording commands, which I guess is why `--legacy` can replay them.
```shell
➜  ~ cat .irbrc
cat: .irbrc: No such file or directory
➜  ~ cat .inputrc
"\e[A": history-search-backward
"\e[B": history-search-forward
set show-all-if-ambiguous on
set completion-ignore-case on
set bell-style none
```

**Comment by ozzyaaron** [comment]
@JonRowe I had the same issue and this fixed it for me https://stackoverflow.com/a/60142403

**Comment by JonRowe** [comment]
Thanks @ozzyaaron that fixed it for me too

**Comment by aycabta** [comment]
@JonRowe I implemented `history-search-backward` and `history-search-forward` by https://github.com/ruby/reline/pull/142, and released a new version of reline gem. Please install the latest version by `gem install reline`.

**Comment by espen** [comment]
I had this issue when using irb and rails console with bundler on Ruby 2.7. irb standalone was working fine. For me the issue was double quotes in .inputrc. Changing it fixed the issue for me.

```
'\e[A': history-search-backward
'\e[B': history-search-forward
```
