### ISSUE TITLE
Signal handling is not restored

### ISSUE THREAD

**Issue by ioquatix** [ruby/irb#95]
https://github.com/ruby/irb/blob/13572d8cdcc31d63f7c1fe6af8e892a60c5727ab/lib/irb.rb#L465-L467

When used in code which already has signal handlers, it seems like the signal handling is never restored.

**Comment by tompng** [comment]
https://github.com/ruby/irb/issues/99
I think this is fixed in irb-1.3.5

**Comment by ioquatix** [comment]
Thanks for closing the issue!
