### ISSUE TITLE
undefined method `encoding_system_needs' for Reline:Module (NoMethodError)

### ISSUE THREAD

**Issue by phykos** [ruby/irb#97]
## Description

What are your expected behavior and actual behavior of your environment?
I launched `irb` and I got this: `undefined method `encoding_system_needs' for Reline:Module (NoMethodError)`
## Terminal Emulator

What's your terminal emulator?
Konsole
## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?
No, the irb command wasn't working so I installed it from gem

**Comment by phykos** [comment]
also, I installed reline with gem and I got: `U+25BD from UTF-8 to US-ASCII (Encoding::UndefinedConversionError)`

**Comment by claytoncova** [comment]
It was happening in my environment. This same error.
I just install reline through "gem install reline" and I removed legacy ".irbrc" from user's home path, 
it worked out..

**Comment by phykos** [comment]
thx, worked too!
