### ISSUE TITLE
^W does not treat the '.' character as a word boundary

### ISSUE THREAD

**Issue by unikitty37** [ruby/irb#979]
## Description

If I have `name = @logged_in_user.full_name` in the command line, with the cursor at the end, and I press ^W, I end up with `name =`.

As dotted chains are common in Ruby, IRB should treat the `.` character as a word boundary by default, leaving me with `name = @logged_in_user` when I press ^W.

## Result of irb_info

Please paste the result of `irb_info` command in IRB.

ex.)

```
irb(main):001:0> irb_info
=>
Ruby version: 2.7.4
IRB version: irb 1.2.6 (2020-09-14)
InputMethod: ReidlineInputMethod with Reline 0.1.5
```

## Terminal Emulator

What's your terminal emulator?

iterm2, 3.5.4beta1. The "." character _is_ configured to be part of a word here.

![image](https://github.com/ruby/irb/assets/139183/98dbdb2a-6dc2-4cbd-9ef4-4d8dd5b7a433)

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

No.

## Other notes

irb is running in a Docker container, using the ruby:2.7.4-slim-bullseye tag. Unfortunately there's a lot of legacy code that prevents upgrading to a more recent version of Ruby (or Rails) so we are stuck with the current versions for now; if this is fixed in later versions but there's a workaround for this setup, it'd be useful to know what it is :)

I have spent a considerable amount of time searching, and gone through https://man.archlinux.org/man/readline.3, and I cannot find how to configure this in .inputrc. Indeed, the linked manpage suggests that _only_ alphanumeric characters are considered to be part of words, which doesn't seem to correspond with what's actually happening…

**Comment by st0012** [comment]
I can still reproduce this in the latest IRB (1.13.2). I wonder if this issue should be transferred to Reline though? @tompng

**Comment by tompng** [comment]
Reline aims to be Readline compatible.
As written in Readline's document, `using white space` part is not configurable.
> [unix-word-rubout (C-w)](https://man.archlinux.org/man/readline.3#unix~2)
Kill the word behind point, using white space as a word boundary. The killed text is saved on the kill-ring.

As a workaround, `M-C-H` (== Alt + delete, assigned to backward-kill-word) will do what you want.

```
irb(main):001> name = @logged_in_user.full_name[Type option + delete]
irb(main):001> name = @logged_in_user.[cursor here]
```

You can assign `\C-w` to `backward-kill-word` in `.inputrc`
```Readline
# Readline >= 0.3.8
"\C-w": backward-kill-word
```
```Readline
# Readline <= 0.3.7
"\C-w": ed-delete-prev-word
```
```Readline
# GNU Readline
# "\C-w" is somehow not re-assignable, maybe bug
```
